### ISSUE TITLE
Nested layouts

### ISSUE THREAD

**Issue by kartoffelkage** [collective/collective.cover#153]
Nesting rows inside columns would allow much more flexible layouts than is currently possible.

Attached an example of a layout that I believe requires nested rows. At the moment I have to put the 2 lower central tiles in a separate row, so they are pushed down by the 'sidebars' unless the content of all the top tiles has matching length:
![Layout](https://f.cloud.github.com/assets/618517/320889/54b0fdc6-9977-11e2-9d69-267fad4c1074.png).

**Comment by hvelarde** [comment]
interesting, but no use case for this.
