### ISSUE TITLE
Cover should emit the layout identifier 

### ISSUE THREAD

**Issue by runyaga** [collective/collective.cover#216]
Currently cover does not emit the layout that is currently used to generate markup.  The outer div should generate something like class="cover-layout-$layoutid"

**Comment by djowett** [comment]
I'm +1 for this, but to be practical it needs to be:

    `class="cover-layout-$layoutid-unmodified"` or  `class="cover-layout-$layoutid-modified"`

BUT is there currently an "Outer div"?

**Comment by hvelarde** [comment]
@djowett that has to be added to the ``class`` attribute in the ``body`` tag; that's the Plone standard.

we can start just by adding ``cover-layout-$layoutid`` as that's the scope of the issue.

**Comment by djowett** [comment]
> ... that has to be added to the class attribute in the body tag; that's the Plone standard.

Fair point

> we can start just by adding cover-layout-$layoutid as that's the scope of the issue.

I suggested appending "modified" & "unmodified" to answer  @marcosfromero valid point - I figure that this is only/mostly useful if Layout has not been modified from the template (as @runyaga mentions)

**Comment by hvelarde** [comment]
@djowett altering the layout changes nothing here as we deal with that on the row, columns and tiles themselves; I prefer to leave things simpler.

do we have a use case to add ``modified`` or ``unmodified``? I guess no, then lets advance step by step.

**Comment by djowett** [comment]
@hvelarde I was just going through the issues list seeing if there was anything I could advance towards a solution, just wanted to add my 2c since I'd thought about this before - with the aim of closing this one off :-)  It seemed to have reached a bit of an impasse.

For myself, I can manage fine with the classes we are now setting on rows & columns since #513 
Maybe this can be closed without action?

**Comment by hvelarde** [comment]
@djowett and I really appreciate that :-)

sorry if I'm tough some times but it's really easy to lost control over a package as complex as this one if we give up about not including more stuff than the one really needed (IMO, of course).

implementing this is very easy; I'll see if I have time later and also I'll document why we're going to need another alpha release before the beta.

**Comment by hvelarde** [comment]
JFTR: [Adding new CSS body classes](http://docs.plone.org/adapt-and-extend/theming/templates_css/css.html#adding-new-css-body-classes)

**Comment by hvelarde** [comment]
@runyaga I implemented the feature; could you please review it and merge it?
