### ISSUE TITLE
classes for rows and maybe columns

### ISSUE THREAD

**Issue by agitator** [collective/collective.cover#284]
thinking of fancy one pagers ...
it would be nice to allow rows and maybe columns to have custom attributes that are displayed as class on the element, so someone could style them not only as the ":nth-child(N)" element of a page but style them as "headerteaser", "moodblock", "contentfooter" and so on ...

**Comment by djowett** [comment]
Probably not an still an issue, but just to add my thoughts here (originally added in issue 481).


1.    Add "headerteaser" in registry.xml about here:

    [{"type": "row", "class": "row headerteaser", ...

2.    Comment out line 250 of layout.py

    # element['class'] = self.row_class

There's no GUI editing or anything, but this should affect any Cover using the modified layout to start with (unless the relevant rows are deleted).

Obviously, you could add a registry.xml & a grid_system.py to your own product & get the same effect.

**Comment by djowett** [comment]
Update: unfortunately when the layout is saved (automatically or manually) any classes originating in registry.xml are lost.
@hvelarde, @agnogueira if I can fix this, will you accept a PR?

**Comment by hvelarde** [comment]
of course!
