### ISSUE TITLE
how to extend tile for 3rd party content types?

### ISSUE THREAD

**Issue by agitator** [collective/collective.cover#324]
i got a custom dx ct based on p.a.event that i wanna display within the contentbody tile.

how would one extend a tile from another package? i don't think an extra tile just for events reasonable or the way tiles should work.

**Comment by espenmn** [comment]
Is it not easier to just add another tile in another product (and just disable the other tile in the control panel) ?

**Comment by hvelarde** [comment]
you can see a couple of examples here:

* https://github.com/collective/collective.nitf/pull/124
* https://github.com/simplesconsultoria/sc.photogallery/pull/3
