### ISSUE TITLE
full-view-tile

### ISSUE THREAD

**Issue by agitator** [collective/collective.cover#325]
somehow connected to #324 

i'd like to see a generic full-view-tile for c.cover that displays title, description and the full content and not only the body text.

this could be done with a similar approach as it's done within the "all content" folder view (folder_full_view).

i also would like a full-view-list tile, to display whole ct items within a listing.

i would be in creating such a tile, if i makes sense in that way within c.cover

or is such functionality hidden somewhere within c.cover?

**Comment by hvelarde** [comment]
I think your use case is covered by Mosaic now.
