### ISSUE TITLE
After installing c.cover, AJAX responses gets wrapped

### ISSUE THREAD

**Issue by rnixx** [collective/collective.cover#331]
After Installing collective.cover, AJAX responses gets wrapped by html / body when performing $.ajax calls.

Response before Install
![before_c cover](https://f.cloud.github.com/assets/246021/1408026/2838551c-3d7a-11e3-90e6-9d76829a1552.png)

Response after Install
![after_c cover](https://f.cloud.github.com/assets/246021/1408030/326b16b4-3d7a-11e3-9874-b46c6fab994c.png)

This breaks scripts depending on returned structure.

IMO it's not a good idea to overwrite generic API's at all.

**Comment by petri** [comment]
It looks like a fix for plone.app.blocks was merged by @datakurre and subsequently released in p.a.b 2.0.0? Can anyone confirm whether that fixes this issue or are some changes still required here?
