### ISSUE TITLE
collective.cover causes a ton of warnings

### ISSUE THREAD

**Issue by href** [collective/collective.cover#362]
Just when I was getting happy with Plone 4.3.2 not throwing any warnings on bin/instance collective.cover comes back to haunt me:

    2013-11-27 09:26:14 WARNING Init Class collective.cover.tiles.configuration_view.DefaultConfigureView has a security declaration for nonexistent method 'browserDefault'
    2013-11-27 09:26:14 WARNING Init Class collective.cover.tiles.configuration_view.DefaultConfigureView has a security declaration for nonexistent method 'publishTraverse'
    2013-11-27 09:26:14 WARNING Init Class collective.cover.tiles.edit.CustomTileEdit has a security declaration for nonexistent method 'browserDefault'
    2013-11-27 09:26:14 WARNING Init Class collective.cover.tiles.edit.CustomTileEdit has a security declaration for nonexistent method 'publishTraverse'
    2013-11-27 09:26:15 WARNING plone.supermodel collective.cover.tiles.collection.ICollectionTile is not an instance of SchemaClass. This can happen if the first base class of a schema is not a SchemaClass. See https://bugs.launchpad.net/zope.interface/+bug/791218
    /Users/denis/Code/people/eggs/grokcore.view-2.8-py2.7.egg/grokcore/view/templatereg.py:261: UserWarning: Found the following unassociated template after configuration: /Users/denis/Code/people/src/collective.cover/src/collective/cover/browser/contentchooser_templates/tree_template.pt
      warnings.warn(msg, UserWarning, 1)
    /Users/denis/Code/people/eggs/grokcore.view-2.8-py2.7.egg/grokcore/view/templatereg.py:261: UserWarning: Found the following unassociated template after configuration: /Users/denis/Code/people/src/collective.cover/src/collective/cover/layout_templates/tileselect.pt
      warnings.warn(msg, UserWarning, 1)
    /Users/denis/Code/people/eggs/grokcore.view-2.8-py2.7.egg/grokcore/view/templatereg.py:261: UserWarning: Found the following unassociated template after configuration: /Users/denis/Code/people/src/collective.cover/src/collective/cover/layout_templates/tile.pt
      warnings.warn(msg, UserWarning, 1)
    /Users/denis/Code/people/eggs/grokcore.view-2.8-py2.7.egg/grokcore/view/templatereg.py:261: UserWarning: Found the following unassociated template after configuration: /Users/denis/Code/people/src/collective.cover/src/collective/cover/layout_templates/generalmarkup.pt
      warnings.warn(msg, UserWarning, 1)
    /Users/denis/Code/people/eggs/grokcore.view-2.8-py2.7.egg/grokcore/view/templatereg.py:261: UserWarning: Found the following unassociated template after configuration: /Users/denis/Code/people/src/collective.cover/src/collective/cover/layout_templates/group.pt
      warnings.warn(msg, UserWarning, 1)
    /Users/denis/Code/people/eggs/grokcore.view-2.8-py2.7.egg/grokcore/view/templatereg.py:261: UserWarning: Found the following unassociated template after configuration: /Users/denis/Code/people/src/collective.cover/src/collective/cover/browser/contentchooser_templates/search_list.pt
      warnings.warn(msg, UserWarning, 1)
    /Users/denis/Code/people/eggs/grokcore.view-2.8-py2.7.egg/grokcore/view/templatereg.py:261: UserWarning: Found the following unassociated template after configuration: /Users/denis/Code/people/src/collective.cover/src/collective/cover/layout_templates/row.pt

There are a couple of warnings from plone.app.tiles too, but the bulk of it is collective.cover. I realize it's not a bug per se, but I really need to get back to this prompt:

    2013-11-27 09:25:48 INFO ZServer HTTP server started at Wed Nov 27 09:25:48 2013
        Hostname: 0.0.0.0
        Port: 8080
    2013-11-27 09:26:16 INFO Zope Ready to handle requests

Isn't it pure bliss? I just need to know if this is just me because I'm missing something or does this happen to everyone? I'd love to fix this.

**Comment by djowett** [comment]
Hi, these warnings can be removed with a new option to grokcore.view.
You need to pin 

    grokcore.view = 2.9    # (or later)

Then set environment variable 

    environment-vars =
        ...
        GROK_DISABLE_TEMPLATE_WARNING on

To sort tests, environment vars have to be set like this (which surprised me, but it does work):

    [testenv]
    GROK_DISABLE_TEMPLATE_WARNING = on

    [test]
    recipe = zc.recipe.testrunner
    ....
    environment = testenv

I reckon that pinning grokcore.view >=2.9 is alright if we want to do that, but that the environment variable set up should be the choice of the end user (though if you want to set it in the test env that's reasonable)

**Comment by hvelarde** [comment]
it was not that easy

**Comment by hvelarde** [comment]
it was that easy; we have an issue somewhere else.
