### ISSUE TITLE
Content choser search problems

### ISSUE THREAD

**Issue by agnogueira** [collective/collective.cover#369]
I found some bugs in the search inside the agregate contet box (Compose tab - Add content)

1. Recent Itens tab
When you open the content choser, you can see only some content types: 
![cover site](https://f.cloud.github.com/assets/1030139/1667326/fd091a4a-5c53-11e3-93e1-edbdc4f4159d.png)
After a search, you can se more content types in results:
![cover site 1](https://f.cloud.github.com/assets/1030139/1667340/1d6b2724-5c54-11e3-997d-5727b3b0292c.png)
We need the same same behavior in both cases

2. Content Tree tab
When you make a search, the number show all the itens in the website, but the result shows only the results inside the actual folder:
![cover site 2](https://f.cloud.github.com/assets/1030139/1667367/6e17fe68-5c54-11e3-9780-e48b483d9883.png)
The number needs to show the number of itens only in the actual folder

**Comment by hvelarde** [comment]
we are addressing those issues in #493 and #494
