### ISSUE TITLE
Expose Slider Options for carrousel tile

### ISSUE THREAD

**Issue by bledwell** [collective/collective.cover#370]
It would be really handy to allow the user to choose more options for the slider. For example, I can in the "galleria.cover_theme.js" file change "transition: slide" to "transition: fade" but that changes all covers that are using the slider tile. It would be handy to expose those options for individual covers.. The ones I can see that could be added are

- transition
- transition speed
- carousel
- thumbCrop
- image_crop

These are just the ones I see listed in the JS file. There might be more, but this is a really nice product! Thanks!

**Comment by hvelarde** [comment]
in fact we want to get rid of the carousel tile.
