### ISSUE TITLE
error when doing GenericSetup export

### ISSUE THREAD

**Issue by fulv** [collective/collective.cover#396]
This is collective.cover 1.0a7 on Plone 4.3.2.

Steps:
- create new Plone site, add collective.cover
- create new cover (no need to do anything else, i.e. layout, compose, or anything)
- in the ZMI, go to portal_setup, Export tab
- click "Export all steps" button

Result:

```
2014-02-21 14:17:56 ERROR Zope.SiteErrorLog 1393021076.560.214411682715 http://localhost:8080/Plone/portal_setup/manage_exportAllSteps
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.GenericSetup.tool, line 593, in manage_exportAllSteps
  Module Products.GenericSetup.tool, line 370, in runAllExportSteps
  Module Products.GenericSetup.tool, line 1038, in _doRunExportSteps
  Module Products.CMFCore.exportimport.content, line 31, in exportSiteStructure
  Module Products.CMFCore.exportimport.content, line 132, in export
  Module Products.GenericSetup.content, line 389, in export
  Module Products.GenericSetup.context, line 476, in writeDataFile
AttributeError: 'DefaultReadFile' object has no attribute 'file'
```

The text object in writeDataFile is:

```
text = <plone.dexterity.filerepresentation.DefaultReadFile object at 0x1079dcdd0>
```

**Comment by idgserpro** [comment]
Just FYI, we tested this in newer versions and the error still exists.

Did the same as @fulv with '1.4b2.dev0' (commit 0b43480578eda2ceb9772d026f19b9f91214cc88): create a Plone Site, create a simple cover with empty layout, go to portal_setup and do "Export All Steps", it gives you the same error.

```
Module ZPublisher.Publish, line 138, in publish
Module ZPublisher.mapply, line 77, in mapply
Module ZPublisher.Publish, line 48, in call_object
Module Products.GenericSetup.tool, line 634, in manage_exportAllSteps
Module Products.GenericSetup.tool, line 399, in runAllExportSteps
Module Products.GenericSetup.tool, line 1249, in _doRunExportSteps
Module Products.CMFCore.exportimport.content, line 36, in exportSiteStructure
Module Products.CMFCore.exportimport.content, line 177, in export
Module Products.GenericSetup.content, line 396, in export
Module Products.GenericSetup.context, line 456, in writeDataFile
AttributeError: 'DefaultReadFile' object has no attribute 'file'
```

In a vanilla Plone 4.3.12, we don't have this problem. We have no idea why this happens.

**Comment by idgserpro** [comment]
Well, the problem isn't with "Export all steps", is with the option

```
Content
Export the site's structure and content.
```

Adding `plone.dexterity.interfaces.IDexterityContainer` (you can test doing http://localhost:8080/Plone/my_cover/manage_interfaces and checking it in `Available Marker Interfaces`) to the cover object and trying to export again in `portal_setup` the error is gone. Since I don't know what is the correct approach to this error I'm leaving this idea here as a **workaround** if someone searches for this traceback, after exporting you should remove the marker interface. @fulv could you check it the workaround works in your situation?

**Comment by hvelarde** [comment]
that's weird, because the content type is not a container; but I think it was probably a container in the past so it may have something left behind.

maybe this? https://github.com/collective/collective.cover/blob/master/src/collective/cover/content.py#L29

**Comment by barseghyanartur** [comment]
I think this issue is still valid.

And it's defnitely a problem of this package.


`Products.GenericSetup/Products/GenericSetup/context.py` near line 443:

```python
security.declareProtected( ManagePortal, 'writeDataFile' )
    def writeDataFile( self, filename, text, content_type, subdir=None ):

        """ See IExportContext.
        """
        if subdir is not None:
            filename = '/'.join( ( subdir, filename ) )

        parents = filename.split('/')[:-1]
        while parents:
            path = '/'.join(parents) + '/'
            if path not in self._archive.getnames():
                info = TarInfo(path)
                info.type = DIRTYPE
                # tarfile.filemode(0755) == '-rwxr-xr-x'
                info.mode = 0755
                info.mtime = time.time()
                self._archive.addfile(info)
            parents.pop()

        info = TarInfo(filename)
        if isinstance(text, str):
            stream = StringIO(text)
            info.size = len(text)
        elif isinstance(text, unicode):
            raise ValueError("Unicode text is not supported, even if it only "
                             "contains ascii. Please encode your data. See "
                             "GS 1.7.0 changes for more")
        else:
            # Assume text is a an instance of a class like
            # Products.Archetypes.WebDAVSupport.PdataStreamIterator, 
            # as in the case of ATFile
            stream = text.file
            info.size = text.size
        info.mtime = time.time()
        self._archive.addfile( info, stream )
```

It's not a text, it's not a unicode, it's something else and that something else should be treated the same way as the `Products.Archetypes.WebDAVSupport.PdataStreamIterator`.

**Comment by hvelarde** [comment]
feel free to open a new issue and provide more details on how to reproduce the problem.
