### ISSUE TITLE
Cannot delete link info from basic Tile

### ISSUE THREAD

**Issue by fredvd** [collective/collective.cover#397]
When you drop a content item on a basic tile, the content is 'connected' to the basic tile and its title and description is copied to the basic tile fields. It is also possible to edit a basic title with a tile and description and not link any content. 

On the compose tab it is possible to override the Title and description and it is possible to add an image, but you cannot 'disconnect' the dropped content item from step one. This means that:
- The title will still link to the content item
- Other linked content fields like the tags if enabled will still show on the field.

When you separate access to the compose tab (content editor domain) from access to the layout tab (site manager) and use templates to set up pref-configured forms, it is necessary that content editor can 'clean' a basic tile. 

Exactly the same concern has the body text tile. If you don't use it, it stays empty, if you drop something on it, it is not possible as an editor to clear the tile again.

**Comment by hvelarde** [comment]
I'm currently reviewing this issue and I found the following:

* banner and carousel tiles are the only ones that allow editing the URL
* basic, collection and list don't allow that (a little weird as carousel tile inherits from list tile)

IMO, we must allow editing URL on basic and list tiles; carousel tile don't make sense.

I'll open another issue to address the list tile.

![Banner Tile](https://user-images.githubusercontent.com/341393/46151794-ed072300-c245-11e8-87ce-13bb2d1f508f.png)

![Basic Tile](https://user-images.githubusercontent.com/341393/46151793-ec6e8c80-c245-11e8-8f3f-f2a97888448d.png)

![List Tile](https://user-images.githubusercontent.com/341393/46151790-ebd5f600-c245-11e8-9aa9-0faba3a245c0.png)

![Carousel Tile](https://user-images.githubusercontent.com/341393/46151792-ec6e8c80-c245-11e8-884e-14b182f0eba6.png)

![Collection Tile](https://user-images.githubusercontent.com/341393/46151791-ec6e8c80-c245-11e8-80c1-cedac7cbe337.png)

**Comment by fredvd** [comment]
Pfeww that's an old issue. :-) 

The carousel tile has  been changed quite a bit since this issue was started, the customisation of every carousel item's fields after dropping was added somewhere 2016 by @frapell IIRC. That's why carousel has evolved away from List Tile. It used to work only by reference.
