### ISSUE TITLE
Carousel Tile has incorrect size, style

### ISSUE THREAD

**Issue by fulv** [collective/collective.cover#414]
This is a bad regression from 1.0a7 to 1.0a8.post1.
To reproduce:
1. Run Plone4.3.3 unified installer
2. Add collective.cover=1.0a8.post1 to the eggs section in buildout.cfg
3. run buildout
4. Create Plone site, and add collective.cover
5. Upload 2 images to site
6. Create a cover, empty layout
7. Go to layout tab, add a carousel
8. Go to compose tab, drag the two images uploaded previously into the carousel
9. Go to view tab

Result:  
- The images extend to basically 100% of the page width, but are blurred.
- The dots of the "galleria-thumbnails" are not overlaid on top of the image, but below it

![cover8](https://cloud.githubusercontent.com/assets/460742/2892915/9a9118d2-d542-11e3-95d1-6bb070d397b0.png)

Expected, from 1.0a7 (this is the result when you repeat the above steps, but replace 1.0a7 in step 2):
- The image is not blurred, and is scaled down to some degree (not sure what the @@images/<UID>.jpeg view does)
- The dots of the "galleria-thumbnails" are on top of the image.

![cover7](https://cloud.githubusercontent.com/assets/460742/2892914/9a8f4e44-d542-11e3-9261-e00921ad902f.png)

**Comment by rodfersou** [comment]
I didn't get what problem still need to be solved here.. a way to set the desired height?

**Comment by hvelarde** [comment]
@rodfersou check @terapyon commit above; anyway, we are not fixing anymore carousel tile bugs here.
