### ISSUE TITLE
Render Cover Page contents outside its context

### ISSUE THREAD

**Issue by petschki** [collective/collective.cover#430]
Hi, I've tried to create a footer viewlet which renders the content of a cover page like this:

    plone.api.content.get_view("layout", context=<cover_context>, request=self.request).render_view()

if I am in the context of the cover page the footer is rendered correctly, but outside the cover context i get an empty grid markup with no tile contents ... has anybody a hint how to solve this?

**Comment by hvelarde** [comment]
@petschki what's the status on this?
