### ISSUE TITLE
Replace Galleria with Cycle2 on carousel tile?

### ISSUE THREAD

**Issue by hvelarde** [collective/collective.cover#442]
after months of using it, we have arrive to the conclusion that [Galleria](http://galleria.io/) is huge and difficult to theme.

some weeks ago we discovered [Cycle2](http://jquery.malsup.com/cycle2/) and we are very pleased with what we saw; we even created a new [Photo Gallery](https://github.com/simplesconsultoria/sc.photogallery) add-on to test it and found it full-featured, really versatile and easy to theme.

Should we replace **Galleria** with **Cycle2**?

**Comment by djowett** [comment]
@hvelarde assuming I can find a few hours to put into cover.tile.galleria, then could you point me in the right direction?

**Comment by hvelarde** [comment]
@djowett thanks! I was thinking of you today :-)

now that I fixed the tests we can start working on this again; unfortunately release 1.0a10 was plenty of bugs and we need to release again fixing them; that will delay the work on this.

I think we must left carousels outside the core of collective cover simply as add-ons and put a big note on the README file stating this on one of the next releases.

I created a ticket to discuss about it: #485

**Comment by djowett** [comment]
@hvelarde is 1.0a10 not recommended for installation?  

I have a target for a project of 2-3 weeks & I'd like URLs in my (galleria) Carousels & just wondering whether to:
a) install that & hope I don't hit errors
b) wait for 1.0a11
c) Stick with old version (from my galleria fork) & Just add an image type with URLs

I know c) will work, but will be tough to support. Do you recommend a) or b) ... (I would probably have a go at cover.tile.galleria in the process)

**Comment by hvelarde** [comment]
I recommend to stay on 1.0a9 but, if you need such feature, you should try master branch (remember to pin on a commit as we're going to be messing around).

we'll be working on 1.0b1 because we need to release for a customer, but I don't know how long it will take.

on the other side, working on [covertile.galleria](https://github.com/collective/covertile.galleria) (the name @mauritsvanrees and @fredvd proposed) will be really appreciated; I think we can work on [covertile.cycle2](https://github.com/collective/covertile.cycle2) on the other side.

**Comment by hvelarde** [comment]
closing this as we are spinning out the carousel tile as stated above.
