### ISSUE TITLE
contentchooser.css "breaks" Products.TinyMCE's hyperlink upload button

### ISSUE THREAD

**Issue by idgserpro** [collective/collective.cover#450]
Tested in a vanilla 4.3.3 Plone Unified Installer with only collective.cover 1.0a9 installed as an Add-On. You need many objects in the folder to test this behavior.

When editing a Document, selecting some text in the textarea and clicking in the hyperlink button of TinyMCE 's toolbar to select an object, the Upload button makes impossible to select lower items.

![error-collective](https://cloud.githubusercontent.com/assets/8203476/4254630/43d86ff6-3aad-11e4-9668-9ce497d4c819.png)

This happens because there's a css rule for `#content` in

https://github.com/collective/collective.cover/blob/master/src/collective/cover/static/contentchooser.css#L1

but there's another div named `content` inside Products.TinyMCE's popup, so collective.cover's `#content` rule is applied as well. Products.TinyMCE popup renders all Plone css in a file called plone.css and the rule is evaluated.

A workaround for this problem in my own theme is to override collective.cover's `#content` rule:

```css
#plonebrowser #content {
    position: static !important;
}
```

The `#content` rule should be more specific and not so generic (should be inside another div#collective-something, perhaps?).

A (somewhat) similar problem: http://stackoverflow.com/questions/21686390/cssing-tinymce-on-a-diazoed-plone-site - this link is useful specially because of plone.css explanation.

**Comment by fredvd** [comment]
Confirmed as in, we had to fix our site-theme as well to compensate for similar problems in the TinyMCE link/image browser popup where the content would dive under the upload button. Will check if this is caused by the cover css.

**Comment by djowett** [comment]
I had a look at this today.  The CSS rule might have been to help position the "Add Content" button, but it isn't required for that right now.  I haven't spotted any issues after removing it here.
A rule in a Plone addon with just `#content` is definitely bad form IMO.

**Comment by idgserpro** [comment]
So the problem in [comment](#issuecomment-55657604), should occur only in [brasil.gov.temas](https://github.com/plonegovbr/brasil.gov.temas). 

@hvelarde we need to check that.

**Comment by hvelarde** [comment]
@idgserpro feel free to provide a fix

**Comment by idgserpro** [comment]
@djowett you tested compose a cover with many titles? In the case that the height is larger than the lateral column?

**Comment by djowett** [comment]
@idgserpro I have just done that & can see no problems.

I think your issue is almost certainly local to your site.  I think you need to set a clear property on your footer... e.g.:

    #wrapper #footer {
        clear: both;
    }

**Comment by idgserpro** [comment]
@djowett If don't are giving problem in collective.cover,this resolves the issue. I think it can be done the merge.

@hvelarde I remembered that this has been fixed in [brasil.gov.portal](https://github.com/plonegovbr/brasil.gov.portal/blob/master/src/brasil/gov/portal/static/css/main.css#L4386)

**Comment by idgserpro** [comment]
Already exists a update step to regenerate the css?

**Comment by djowett** [comment]
@idgserpro that's a really good question, from looking at the code I think so, but I'm not used to upgrade steps, so @hvelarde can you please confirm?

**Comment by hvelarde** [comment]
the current upgrade step already cooks both resource registries: https://github.com/collective/collective.cover/blob/master/src/collective/cover/upgrades/v11/configure.zcml
