### ISSUE TITLE
Cover breaks when remove image of a item

### ISSUE THREAD

**Issue by rogeriocdluiz** [collective/collective.cover#480]
When a image of a item (News Item for example ) in cover is removed  the cover breaks.

The same occurs when remove a image for a item used in carrousel.

Versions
    Collective.Cover 1.0a9.
    Plone 4.3.3 (4308)
    CMF 2.2.7
    Zope 2.13.22
    Python 2.7.6 (default, May 15 2014, 14:03:26) [GCC 4.3.4 [gcc-4_3-branch revision 152973]]
    PIL 2.3.0 (Pillow)

Before
![before](https://cloud.githubusercontent.com/assets/5632379/6174406/9e4f961c-b2d5-11e4-9bf9-c749f4e025ac.jpg)

After
![after1](https://cloud.githubusercontent.com/assets/5632379/6174405/9e4f18a4-b2d5-11e4-9051-c84dec4f8fc3.jpg)

![after2](https://cloud.githubusercontent.com/assets/5632379/6174404/9e4d1d56-b2d5-11e4-94e2-7dce20dd4860.jpg)

**Comment by hvelarde** [comment]
could you please give more information? which tile are we talking about on the first problem you mentioned?

**Comment by rogeriocdluiz** [comment]
Ok.

In the first image i have the cover configured. Its all ok. If a user removes a image from any news in cover the layout breaks.

Example:

If a user removes a image of a news item that is in Carrousel the layout breaks. The same occurs if a user remove a image of any other news item in the cover.

**Comment by rodfersou** [comment]
@rogeriocdluiz @hvelarde I could not reproduce the problem with collective.cover at master branch.
@rogeriocdluiz could you please try to reproduce the problem with master branch, and share the steps to make it happen?

**Comment by rogeriocdluiz** [comment]
Ok. I will test soon.

**Comment by rodfersou** [comment]
@rogeriocdluiz any luck with that?

**Comment by rogeriocdluiz** [comment]
Same problem! The test was done in a new installation....


![cover1](https://cloud.githubusercontent.com/assets/5632379/8071952/696052a4-0ee5-11e5-9718-ca656ffc1a98.jpg)
![cover2](https://cloud.githubusercontent.com/assets/5632379/8071949/69437d32-0ee5-11e5-8fe4-e3a3da4d1997.jpg)
![cover3](https://cloud.githubusercontent.com/assets/5632379/8071950/694df352-0ee5-11e5-8f09-317ea941d0d9.jpg)
![cover4](https://cloud.githubusercontent.com/assets/5632379/8071953/6968ca74-0ee5-11e5-8d44-b1ffa4a1e330.jpg)
![cover5](https://cloud.githubusercontent.com/assets/5632379/8071951/694e982a-0ee5-11e5-8828-c188e2880794.jpg)




![cover6](https://cloud.githubusercontent.com/assets/5632379/8072162/9b0945a6-0ee8-11e5-8b51-1ab3d993a17b.jpg)

**Comment by hvelarde** [comment]
I just tested against 5 different tiles (banner, basic, list, carousel and collection) and I wasn't able to reproduce any problem.

**Comment by rogeriocdluiz** [comment]
Hi. 
I tested and the problem has resolved, but i needed to set plone.app.blocks to version 1.1.1.

Thank you.

**Comment by hvelarde** [comment]
@rogeriocdluiz and that was clearly documented from the very beginning: https://github.com/collective/collective.cover#installation
