### ISSUE TITLE
Row Settings

### ISSUE THREAD

**Issue by veldman** [collective/collective.cover#481]
Hi,

I am trying to add settings to a row with for example, a row title and color. What I tried to do is the following: 
- add to the json string that is stored in a row, but when the layout will be saved, the json will be overwritten.
- create my own annotation schema on the current context, but the rows do not have any way of telling them apart from each other, thus resulting in wrong titles on wrong rows etc.

Have you guys already thought about adding a row setting or do you have suggestions on where to go?

**Comment by hvelarde** [comment]
I think I don't understand... why do you need this? could you please post some mockup of the final result you're expecting?

**Comment by agnogueira** [comment]
I think is related to #284

**Comment by djowett** [comment]
Hey @veldman , I just played about with this. Try this to start you off:

1. Add headerteaser in registry.xml about here:

      <element key="Layout A">[{"type": "row", "class": "row **headerteaser**", ...

2. Comment out line 250 of layout.py 

     # element['class'] = self.row_class

3. Let us know what happens.

Obviously, you could add a registry.xml & a grid_system.py to your own product & get the same effect.

I think this works for #284 also

**Comment by veldman** [comment]
Sorry, I haven't carefully  explained my issue so far.

What I am looking for is a setting directly on the row, so I can add a title on a row not on a single tile. To visualise it, I created a couple of images.

For the layout edit, I would like direct settings on a row like tiles that have it enabled. Like here http://i.imgur.com/zFaIVoh.png. Where you would be able to enable / disable specific settings for the row, like on a tile.

In the compose screen I would like to edit the specific fields, so I would be able to set a title for example, like this: http://i.imgur.com/nCXSQzR.png.

The result would be a title of a row, like this: http://i.imgur.com/5EXWsd8.png

What I can do is store the fields needed for the rows on the current context with annotations, but I have no way of identifying which row is which, especially after rows have been dragged and dropped to other places. This is because rows are not distinguishable of each other, only by their position in the JSON storage.

Am I missing an obvious way to maybe store it on a row, or do you have another solution for this specific problem maybe?

**Comment by djowett** [comment]
Ah, ok, well my solution may not help so much (though if you only need a CSS class on a row then it will help for that).

**Comment by puittenbroek** [comment]
To add to this issue, @veldman is a collegeau of mine ;)
We noticed that rows are not unique in anyway.
What would help, is that rows of some form of UID we could work with.
We can manage saving the information somewhere in annotations, but without something unique to work with, you would need -a lot- of javascript event handling to ensure your info is up to date.
(Drag&drop of rows and such)

**Comment by hvelarde** [comment]
IMO, adding a row with a tile on top of your row will solve your use case without any additional change to the code.

this package is already quite complex and adding such feature will add a lot more complexity to it, so I'm :-1: on this one.

**Comment by hvelarde** [comment]
I'm closing this as we are going to address the enhancement proposed on #284 only.
