### ISSUE TITLE
New collective.js.bootstrap asks for plone.app.jquery >= 1.8.3 making it inconsistent with Plone 4.3.x branch

### ISSUE THREAD

**Issue by idgserpro** [collective/collective.cover#492]
The new [collective.js.bootstrap released in March](https://pypi.python.org/pypi/collective.js.bootstrap/3.3.1.1) asks for [plone.app.jquery>=1.8.3](https://github.com/collective/collective.js.bootstrap/commit/9e3539d78a186d860edd826d216166e67f30f651) but Plone 4.3.x branch [recommends 1.7.2](http://dist.plone.org/release/4.3-latest/versions.cfg).

We suggest pinning collective.js.bootstrap in collective.cover's setup.py to 

```collective.js.bootstrap < 3```

to avoid problems in Plone 4.3.x branch.

@hvelarde Can you check this issue? Do you agree with the solution above?

**Comment by hvelarde** [comment]
I have no strong opinion on that; currently collective.cover is compatible with ``plone.app.jquery = 1.8.3`` under Plone 4.3 (as you can see on [Travis CI](https://travis-ci.org/collective/collective.cover)) but I don't know if it is compatible with the latest version of collective.js.bootstrap.

we need to verify first if we can upgrade to ``collective.js.bootstrap = 3.3.1.1`` without problems.

if not, we can set the restriction.

**Comment by hvelarde** [comment]
on the other hand, I really don't know if we want to depend on Bootstrap; we have to review that at some point.

**Comment by davidjb** [comment]
The latest collective.js.bootstrap requires jQuery 1.9.1 according to my JS console messages.  The package doesn't pin it, though.

**Comment by pigeonflight** [comment]
@davidjb I've had this issue with a project where I needed a newer version of plone.app.widgets which relied on JQuery 1.9.x. My solution was to also include jquery.migrate. jquery.migrate is a jquery plugin which backports some of the deprecated code from jQuery 1.8.x and below. It solved my problems.

The screenshot below illustrates how the jquery.migrate plugin reimplements .browser() and .fn.live(). This is all running on jQuery 1.9.x, but collective.cover is working for me. Hope you find it useful.

![screenshot 2015 04 02 at 7 23 06 am](https://cloud.githubusercontent.com/assets/31827/6963866/60f3039e-d909-11e4-98a4-85a3e6077fff.png)
