### ISSUE TITLE
Performance issues when accessing the content tree

### ISSUE THREAD

**Issue by hvelarde** [collective/collective.cover#494]
When accessing the content tree tab on the content chooser we have noticed that the current script is far from optimal and sometimes just hangs:

![selection_002](https://cloud.githubusercontent.com/assets/341393/6925769/245a0ac4-d7b8-11e4-8a2e-ea197bc5ea71.png)

Things to be fixed:

* we should list all elements inside the folder
* folder contents should be shown with its original order, regardless if they are items or other folders (just like folder contents tab in Plone)
* when filtering we should wait for the user to stop typing before making a search (check Plone's [livesearch script](https://github.com/plone/Products.CMFPlone/blob/4.3.x/Products/CMFPlone/skins/plone_ecmascript/livesearch.js))
* filtering should be done only on the title index
* an spinner should be shown to let the user know there is a filtering in progress
* after filtering the order must continue unchanged
* we should show the item description in the title attribute
* we should use the ``grab`` cursor when selecting an item and ``grabbing`` when dragging it

**Comment by rodfersou** [comment]
I don't know why, but #kss-spinner id changed by #ajax-spinner (I think it is a plone update) so need to change some javascripts

**Comment by hvelarde** [comment]
merged
