### ISSUE TITLE
Incompatible with jQuery 1.9+ (pin to 1.8.3?)

### ISSUE THREAD

**Issue by davidjb** [collective/collective.cover#498]
As collective.cover uses the ``$.live`` method (maybe other things too), it's incompatible with jQuery 1.9+.  plone.app.jquery should be pinned in this setup.py to be prevent install with an incompatible version.

Somewhat related to #492 regarding pinning.

**Comment by hvelarde** [comment]
Plone is not compatible with jQuery 1.9 neither as you can see in #413 and #455.

Please, use the [issue_420 branch](https://github.com/collective/collective.cover/tree/issue_420) to work on that issue.

**Comment by hvelarde** [comment]
In that branch there's even a Travis CI build for jQuery v1.9.1.2 as you can see here: https://travis-ci.org/collective/collective.cover/builds/38497005
