### ISSUE TITLE
Ship with more than one grid system

### ISSUE THREAD

**Issue by rodfersou** [collective/collective.cover#504]
We need to ship cover with more than one grid system by default, so we will add 2 new 12-columns grid systems based on Bootstrap 2 and Bootstrap 3.

Bootstrap 2 (12 columns) will be the default one for new installations; for upgrades Deco (16 columns) will remain unchanged.

We need an upgrade step to update all layouts stored in the site.

**Comment by hvelarde** [comment]
For me, this also closes #357
