### ISSUE TITLE
Which issues must be closed before 1.0b1 release?

### ISSUE THREAD

**Issue by hvelarde** [collective/collective.cover#509]
Currently we have around [15 issues marked as open bugs](https://github.com/collective/collective.cover/issues?q=is%3Aopen+is%3Aissue+label%3Abug) of the package; which of them must be closed for release 1.0b?

For me this are blockers:

- [x] https://github.com/collective/collective.cover/issues/480
- [x] https://github.com/collective/collective.cover/issues/450

Beyond [removing carousel tile](https://github.com/collective/collective.cover/issues/485), is there any other enhancement that must be included in 1.0b1?

All carousel bugs must be ignored and moved to the new [covertile.galleria](https://github.com/collective/covertile.galleria) repository:

- [ ] https://github.com/collective/collective.cover/issues/370
- [ ] https://github.com/collective/collective.cover/issues/414
- [x] https://github.com/collective/collective.cover/issues/495

Are there any other blockers?

**Comment by fredvd** [comment]
I'd like to have #495  (with pull request #500) merged as it fixes editing the carousel compose model for sited editors without the Manager role as soon as any content dropped on the carousel expires. 

Can we at least merge finished branches/pull request for carousel in the master before we split of the galleria carousel tile?

**Comment by djowett** [comment]
I don't see any other issues to hold it up, though I think Fred's request is reasonable, even if not so practical.

However, from using master just now, you do realise that using `api.env.plone_version()`
means you need to wait for a release of plone.api?

**Comment by hvelarde** [comment]
@djowett is there since version 1.2, almost a year ago:

https://github.com/plone/plone.api/commit/16bc0c731f5f55ac2fbed63852296c488e3c2796
https://pypi.python.org/pypi/plone.api

**Comment by hvelarde** [comment]
@fredvd on #500 I'm only waiting for a fix on the associated permission of the ``show_inactive`` option.

what other PR are finished and still open on carousel tile?

**Comment by djowett** [comment]
@hvelarde Ah, bad reading of GH history  & sorry I had a pin on it for some obscure reason.

**Comment by petri** [comment]
#331? It's been an ugly bug that has been breaking other stuff - and it looks like it may be easy to close since a required fix in plone.app.blocks has been merged by @datakurre and subsequently released in p.a.b 2.0.0.

**Comment by hvelarde** [comment]
@petri including p.a.blocks will drop support for Plone 4.2; we are close to a 1.0b1 release and we don't want to leave some important bug fixes out of it as we have some sites to maintain.

I would prefer to defer that for 1.0b2.

**Comment by fredvd** [comment]
I'll be haveing another try at testing master today as it is on current master with our biggest project using it. 1.0b1. Which work is left for 1.0b1, the separation of galleria and adding a released version of covertile.cycle2 by default with instructions on how to stick to galleria instead?  Can I help somewhere with that?

**Comment by hvelarde** [comment]
@fredvd I will work on moving the code later today; please review the list of open issues and try to identify which ones are important but we are missing.

**Comment by petri** [comment]
ping - is there anything blocking us from a release? (I updated @hvelarde 's list at top wrt #480 that's been fixed - also #331 is fixed now). But #370 & #414 are still open, are those needed for 1.0b1 or is it better to push this release out now?

**Comment by hvelarde** [comment]
@petri frankly I don't know if we will ever release a 1.0b1 of this package; my view has changed over the last months and there are 2 issues that I have no resources to deal with right now: removal of carousel and PFG tiles.

if we don't find time/resources to deal with that (and is not trivial) I think I would prefer at some point just open a new 2.x branch and get rid of all the crap when support for Plone 5.0 is ready.

on the mean time, for a new release I want: support for jQuery 1.9 and test plone.app.blocks 3.x as @datakurre told me we may get compatibility with Plone 4.2 back with that.

I'm going to close this issue and work on those, ok?

any feed back on which other issues we need to close before a new release is welcome.
