### ISSUE TITLE
Is contextPopup used?

### ISSUE THREAD

**Issue by djowett** [collective/collective.cover#521]
If not we could delete:

* [static/jquery.contextmenu.js](https://github.com/collective/collective.cover/blob/master/src/collective/cover/static/jquery.contextmenu.js)
* [static/jquery.contextmenu.css](https://github.com/collective/collective.cover/blob/master/src/collective/cover/static/jquery.contextmenu.css)

From comments in the JS file:
    Usage:
 
    $('.something').contextPopup({
      title: 'Some title',
      items: [
        {label:'My Item', icon:'/some/icon1.png', action:function() { alert('hi'); }},
        {label:'Item #2', icon:'/some/icon2.png', action:function() { alert('yo'); }},
        ....

But no other reference to contextPopup in the package....

**Comment by hvelarde** [comment]
I have no idea, @djowett, open a branch and let Travis do the work.

**Comment by djowett** [comment]
@hvelarde I guess it isn't then.... would you care to merge?

**Comment by hvelarde** [comment]
thank you! removing useless code is as important as adding new features :-)
