### ISSUE TITLE
Same ID for tiles on IE10/11

### ISSUE THREAD

**Issue by veldman** [collective/collective.cover#526]
When adding two new tile to a column (with boostrap3 grid) they will have the same ID. This results in storing the data under the same tile and getting an exact copy of each other. This only happens in IE10/11. 

![screen shot 2015-06-03 at 14 45 23](https://cloud.githubusercontent.com/assets/4149042/7960238/3b620522-09ff-11e5-9879-11fac3cb936c.png)

See attached screenshot of resulting HTML.

**Comment by hvelarde** [comment]
we are working on this now; follow #554
