### ISSUE TITLE
Do not use overrides.zcml

### ISSUE THREAD

**Issue by djowett** [collective/collective.cover#528]
Unless I've remembered wrong, overrides.zcml (added in #527) should really only be used by "end products" - i.e. a site's policy or theme.  Using it in an addon such as this makes things difficult (though perhaps not impossible) for integrators to override if they need to.

Taking a lead from this theme, we should be able to drop the use of overrides.zcml
https://github.com/sixfeetup/plonetheme.simplecolor/blob/master/plonetheme/simplecolor/browser/configure.zcml#L58
Using the layer "collective.cover.interfaces.ICoverLayer"

**Comment by hvelarde** [comment]
@djowett can you document your concern? where did you read about it?

also, if this option on **plonetheme.simplecolor** could be an alternative, it would be nice to [update the documentation](http://docs.plone.org/adapt-and-extend/theming/templates_css/css.html#adding-new-css-body-classes) to reflect that.

**Comment by fredvd** [comment]
@hvelarde the documentatio you point to doesn't mention using overrides.zcml as far as I can see, it describe that you can override the registration, but that can be done by being more specific than the default registration in plone.app.layout. 

From looking at the registration I guess by specifying  for="collective.cover.interfaces.ICover" it should already be more specific than the default registration, but adding a browserlayer (layer=) like the one in plonehteme.simplecolor prevents the registrattion being active without the add'on being installed.

@djowett Correct me if I'm wrong if this is what you meant ;-)

**Comment by djowett** [comment]
> @djowett can you document your concern? where did you read about it?

Despite looking I can't find where I read it - maybe I dreamt it :-o 
but I did find a reference on [nabble | Plone Product Developers](http://plone.293351.n2.nabble.com/How-to-override-an-adapter-which-is-already-overridden-by-CMFPlone-td781690.html), which says:

> "The point here is that Plone as a framework shouldn't use
overrides at all. This is exactly to avoid problems like the
one that you are encountering now. Overrides should be the
last resort of specific applications (e.g., a specific
site's policy product)." 

and a comment from IRC this morning from @lentinj :
> overrides.zcml is like !important in CSS, it's generally a last resort
> Especially in an add-on, where people might want to override your overrides

I don't mind updating the docs, if I've got decent technical backing (not just my own opinion)

**Comment by djowett** [comment]
Thanks @fredvd 
> @hvelarde the documentation you point to doesn't mention using overrides.zcml as far as I can see, it describe that you can override the registration, but that can be done by being more specific than the default registration in plone.app.layout, you don't need an overrides.zcml for that.
+1

> From looking at the registration I guess by specifying for="collective.cover.interfaces.ICover" it should already be more specific than the default registration, but adding a browserlayer (layer=) like the one in plonetheme.simplecolor prevents the registration being active without the add-on being installed.
Not what I meant - I missed the fact it was already more specific but +1 for the point anyway ;-)

**Comment by hvelarde** [comment]
@fredvd you are completely right; my mistake; @djowett please feel free to fix this, seems to be very easy.

**Comment by djowett** [comment]
@hvelarde - yep 'twas easy #531
