### ISSUE TITLE
Upgrade step for simplified data layout (simplify_layout) corrupts covers in existing setups

### ISSUE THREAD

**Issue by fredvd** [collective/collective.cover#530]
commit f740406f09f197c8a3bc6bc4163febc4cf7514af changes the structure of existing covers/layouts where all the column sizes seem to be reset to 1 column.  Will investigate later today, have a meeting first. 

Before:
![before](https://cloud.githubusercontent.com/assets/394784/8228594/5a2e2bd6-15b0-11e5-9040-81a1ad28b7e6.gif)

After:
![after_gif](https://cloud.githubusercontent.com/assets/394784/8228598/5eeb9154-15b0-11e5-8cd3-a77e2dcd54e1.gif)

**Comment by hvelarde** [comment]
@rodfersou can you please take a look?

**Comment by rodfersou** [comment]
@fredvd could you share this cover layout with us to investigate what happen?

**Comment by fredvd** [comment]
Here's a dump of obj.cover_layout before and after the upgrade. (http://www.vmm.be front page)

Before update:
```
'[{"type": "row", "children": [{"data": {"layout-type": "column", "column-size": 12}, "type": "group", "children": [{"tile-type": "collective.cover.carousel", "type": "tile", "id": "ad5449954e5c49ba9af021e7b20a4614"}], "roles": ["Manager"]}]}, {"type": "row", "children": [{"data": {"layout-type": "column", "column-size": 6}, "type": "group", "children": [{"tile-type": "vmm.tiles.lookingfor", "type": "tile", "id": "d10e3a2de5ee42bcb361f37c48ca4e8b"}], "roles": ["Manager"]}, {"data": {"layout-type": "column", "column-size": 6}, "type": "group", "children": [{"tile-type": "vmm.tiles.lookingfor", "type": "tile", "id": "c0d64b508b024643aa5fd1e5c1ad7559"}], "roles": ["Manager"]}]}, {"type": "row", "children": [{"data": {"layout-type": "column", "column-size": 6}, "type": "group", "children": [{"tile-type": "collective.cover.richtext", "type": "tile", "id": "b7a0d4dbde2f4ca69eedf4496eebd3bb"}, {"tile-type": "collective.cover.list", "type": "tile", "id": "b49b9014a40541e286dabaafc8630a6a"}, {"tile-type": "collective.cover.list", "type": "tile", "id": "c96f7d594c80416f93cc0cd790f08964"}], "roles": ["Manager"]}, {"data": {"layout-type": "column", "column-size": 6}, "type": "group", "children": [{"tile-type": "collective.cover.richtext", "type": "tile", "id": "ce24af8797af437bb581da13e4d48708"}], "roles": ["Manager"]}]}]'
```

2015-06-18 19:39:44 INFO collective.cover "/plone/welkom" was updated

After update: 
```
u'[{"type": "row", "children": [{"type": "group", "children": [{"tile-type": "collective.cover.carousel", "type": "tile", "id": "ad5449954e5c49ba9af021e7b20a4614"}], "roles": ["Manager"], "column-size": 12}]}, {"type": "row", "children": [{"type": "group", "children": [{"tile-type": "vmm.tiles.lookingfor", "type": "tile", "id": "d10e3a2de5ee42bcb361f37c48ca4e8b"}], "roles": ["Manager"], "column-size": 6}, {"type": "group", "children": [{"tile-type": "vmm.tiles.lookingfor", "type": "tile", "id": "c0d64b508b024643aa5fd1e5c1ad7559"}], "roles": ["Manager"], "column-size": 6}]}, {"type": "row", "children": [{"type": "group", "children": [{"tile-type": "collective.cover.richtext", "type": "tile", "id": "b7a0d4dbde2f4ca69eedf4496eebd3bb"}, {"tile-type": "collective.cover.list", "type": "tile", "id": "b49b9014a40541e286dabaafc8630a6a"}, {"tile-type": "collective.cover.list", "type": "tile", "id": "c96f7d594c80416f93cc0cd790f08964"}], "roles": ["Manager"], "column-size": 6}, {"type": "group", "children": [{"tile-type": "collective.cover.richtext", "type": "tile", "id": "ce24af8797af437bb581da13e4d48708"}], "roles": ["Manager"], "column-size": 6}]}]'
```

**Comment by rodfersou** [comment]
As you can see in this image, it just change the way column-size are applied:
![diff](https://cloud.githubusercontent.com/assets/131209/8309620/c4ccd1dc-19a1-11e5-9928-ac7f4e531d89.png)
That's exactally what should happen in this upgrade step, so I don't know what is the problem.

**Comment by rodfersou** [comment]
The layout-type property id not necessary, so it was removed.

**Comment by rodfersou** [comment]
The code of c.cover should understand the new structure

**Comment by hvelarde** [comment]
@fredvd could you confirm this?

**Comment by fredvd** [comment]
The problem was that our custom Grid system wasn't using the internally changed column-size yet so all columns were 'reset' to size 1. I already figured out if all else was ok our only other customisation was the gid system (heck we added customisable grid to cover :-P ).  and found @djowett's updated to the developer docs.

I've added a warning to the developer docs that 1.0a10 > needs an update to custom grid systems and i've put it in the changes so other people can see this. @rodfersou even if it's internal data changes, please mention backward incompatible changes in the main CHANGES log  with a warning, it's the only way contributors to c.cover can figure out incompatible changes without hunting through all the changes on github themselves. IGridSystem is an 'official' extension for integrators to configure cover afaics.

**Comment by fredvd** [comment]
Closes by fixes to a custom GridSystem as per the updates found in b63ff677aa370f78af91901185a2308c75cbaee3
