### ISSUE TITLE
Make date fields in tiles configurable

### ISSUE THREAD

**Issue by rodfersou** [collective/collective.cover#534]
Today we present date as `<p>Jul 09, 2015 10:27 AM</p>`.

I think we should present it with 2 tags time this way:

    <p>
      <time datetime="2015-07-09T10:27:56-03:00">
        <spam class="date-part">Jul 09, 2015</spam>
        <spam class="time-part">10:27 AM</spam>
      </time>
    </p>

Resources:
* http://www.webmonkey.com/2010/02/add_semantic_value_to_your_pages_with_html_5/
* http://diveintohtml5.info/semantics.html
* https://html.spec.whatwg.org/multipage/semantics.html#the-time-element
* http://www.w3schools.com/tags/tag_time.asp

**Comment by hvelarde** [comment]
@rodfersou please use the same markup as here: https://github.com/collective/collective.liveblog/blob/master/src/collective/liveblog/browser/templates/update.pt#L80:L86

**Comment by rodfersou** [comment]
@hvelarde fine, after our chat about this issue, we agreeded that I'll create a [new widget](https://github.com/collective/collective.cover/tree/master/src/collective/cover/tiles/configuration_widgets) with a configuration option.

**Comment by rodfersou** [comment]
Closed in this pull request https://github.com/collective/collective.cover/pull/535/files
