### ISSUE TITLE
Drop support for Plone 4.2?

### ISSUE THREAD

**Issue by hvelarde** [collective/collective.cover#539]
In order to merge #516 (which fixes #331) we need to drop support for Plone 4.2; anybody against?

**Comment by hvelarde** [comment]
merged; Plone 4.2 no longer supported

**Comment by datakurre** [comment]
@hvelarde 

I'd expect you to be compatible also with plone.app.blocks 3.x (we did change behavior used in Mosaic so much that did major release, but probably didn't affect cover usage of blocks). Yet, I also made one more release for 2.x branch. 2.2.0 should be Plone 4.2 compatible :)

https://travis-ci.org/plone/plone.app.blocks/builds/83252408

**Comment by djowett** [comment]
I'm not against this - but dropping compatibility of a major plone 
version should IMO:
- bump the version number significantly (1.1?)
- be documented in the README



On 14/08/15 17:56, Héctor Velarde wrote:
>
> In order to merge #516 
> <https://github.com/collective/collective.cover/pull/516> (which fixes 
> #331 <https://github.com/collective/collective.cover/issues/331>) we 
> need to drop support for Plone 4.2; anybody against?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/collective/collective.cover/issues/539>.
>

-- 
Daniel Jowett

*Jowett Enterprises Ltd*
Tel: 0333 3 553 773
Mobile: 07870 667 126
daniel@jowettenterprises.com
www.jowettenterprises.com

**Comment by hvelarde** [comment]
@djowett we're not dropping compatibility with a major Plone version; we're dropping compatibility with an already unsupported branch of a major version: 4.2; and yes, is documented on the README, but I'll add a big warning there later.

@datakurre I'll test v2.2.0 later then.
