### ISSUE TITLE
Check what we will need to support Bootstrap 4

### ISSUE THREAD

**Issue by rodfersou** [collective/collective.cover#542]
http://blog.getbootstrap.com/2015/08/19/bootstrap-4-alpha/

**Comment by hvelarde** [comment]
what about waiting first to be stable :-)

**Comment by rodfersou** [comment]
it is almost there, and the way to use the grid should not change too much..

**Comment by djowett** [comment]
and please remember not all c.cover users do bootstrap too!

**Comment by rodfersou** [comment]
@djowett I know, we already support [deco 16 and bootstrap 2 and bootstrap 3](https://github.com/collective/collective.cover/blob/master/src/collective/cover/layout.py#L269-L338) I just want to add another option :)

**Comment by rodfersou** [comment]
looks like the grid system didn't change [1](https://github.com/twbs/bootstrap/blob/v4.0.0-alpha/scss/bootstrap-grid.scss#L14-L25) [2](https://github.com/twbs/bootstrap/blob/v4.0.0-alpha/scss/mixins/_grid-framework.scss#L6-L46) they just add the `xl-` prefix for extra large desktops (before we had to use a plugin to get this prefix)

So for me it looks like we will need to change `collective.js.bootstrap` first and add another grid class.

When we deal with responsive layouts we will worry about `xl-` prefix just for bootstrap 4.

**Comment by hvelarde** [comment]
no use case for this right now.
