### ISSUE TITLE
RichText Edit broken when plone.app.widgets is installed

### ISSUE THREAD

**Issue by mtrebron** [collective/collective.cover#543]
The edit popup for RichText content is missing the HTML editor. To reproduce:

Create a new Plone 4.3.6 instance 
Add a new Plone site and check only plone.app.contenttypes
Notice how the edit page view is using p.a.widgets.
Return to the add-on screen and install collective.cover
Create a new cover page, add a rich text tile to the layout and attempt to edit the tile.

Possibly related: https://github.com/collective/collective.cover/issues/418

Unfortunately, I need p.a.w 1.8.0 for this project, because its fixes 404 errors when looking @@qsOptions and @@getVocabulary in the LRF when using plone.app.multilingual 

Any help or workaround is welcome... 

Versions according to http://dist.plone.org/release/4.3.6/versions.cfg

Pinned:
plone.app.contenttypes = 1.1b5
collective.js.bootstrap = 2.3.1.1
plone.app.blocks = 1.1.1
plone.app.tiles = 1.0.1

Picked:
Versions had to be automatically picked.
The following part definition lists the versions picked:
[versions]
i18ndude = 3.4.2
icalendar = 3.8.4
plone.app.event = 1.2.7
plone.app.multilingual = 2.0.0
plone.event = 1.1
plone.formwidget.recurrence = 1.2.5
plone.recipe.precompiler = 0.6
plone.tiles = 1.2
wildcard.fixpersistentutilities = 1.1b7
z3c.jbot = 0.7.2

Required by:
plone.app.event==1.2.7
Products.DateRecurringIndex = 2.1

Required by:
plone.app.event==1.2.7
collective.elephantvocabulary = 0.2.4

Required by:
collective.cover==1.0a11
collective.js.galleria = 1.2.5

Required by:
collective.cover==1.0a11
plone.api = 1.2.1

Required by:
plone.app.tiles==1.0.1
plone.app.drafts = 1.0b3

Required by:
plone.app.contenttypes==1.1b5
plone.formwidget.querystring = 1.1.5

**Comment by mtrebron** [comment]
Update on the above:

My use case was resolved by staying away completely from plone.app.widgets. IMO there should be a note in the readme about this. 

FWIW, my working version pins, using TinyMCE and replacing the subject field with collective.plone4widgetsfallback - in case anyone else stumbles across this issue:

plone.app.multilingual = 2.0.0
plone.app.contenttypes = 1.1b5
collective.cover = 1.0.a11

plone.app.event = 1.1.4
plone.z3cform = 0.8.1
plone.theme = 2.1.5

**Comment by hvelarde** [comment]
this was already reported by @fulv in #418 and there's some work on:

https://github.com/collective/collective.cover/pull/469

I have no idea on how to solve it and have no time/resources to take care of it now.

contributions are welcome.

**Comment by petschki** [comment]
@mtrebron actually I forked c.cover and moved the templates to use patterns for configuration data editing see https://github.com/petschki/collective.cover (just synced it with master right now). @hvelarde I'm not shure about how to handle both worlds (Plone 4.x w/o widgets and Plone 4.x with p.a.contenttypes and p.a.widgets) ... maybe you have a suggestion for me, so I can contribute that code to the collective.

**Comment by hvelarde** [comment]
@petschki I'm not sure neither but I think that could be the future when we have a version compatible with Plone 5.

@cguardia @alecpm @cewing what do yuo guys think?

@rodfersou FYI

**Comment by alecpm** [comment]
@hvelarde this issue has come up for us on our Plone 5 branch, and we're planning to look into it soon I think.

**Comment by hvelarde** [comment]
@petschki maybe you can collaborate with @alecpm

**Comment by hvelarde** [comment]
@rodfersou I can confirm the issue with `plone.app.widgets==1.8.0`
