### ISSUE TITLE
Layout changes are not being saved with plone4.csrffixes 1.0.6

### ISSUE THREAD

**Issue by agitator** [collective/collective.cover#558]
works with plone4.csrffixes-1.0.4

plone 4.3.6

**Comment by rodfersou** [comment]
Hi @agitator I try to reproduce de problem with some of our buildouts without success..

Please take a look if you pin these versions with plone4.csrffixes 1.0.6:

´´´
plone.keyring = 3.0.1
plone.locking = 2.0.8
plone.protect = 3.0.14
´´´
