### ISSUE TITLE
TogetherJS integration on composer tab.

### ISSUE THREAD

**Issue by cleberjsantos** [collective/collective.cover#569]
We would try use of [togetherjs](https://togetherjs.com/) in composer tab to provide a collaborative editing?

* http://www.unknownerror.org/opensource/mozilla/togetherjs/v/youtube_video/H1dHuBb5vGU/togetherjs-integration-with-plone-4-3

* https://github.com/simahawk/collective.js.togetherjs

* https://pypi.python.org/pypi/zopyx.together

**Comment by cleberjsantos** [comment]
@hvelarde @rodfersou @agnogueira

**Comment by hvelarde** [comment]
just test it ;) but, if we need to modify something in this package, I'm -1

**Comment by rodfersou** [comment]
Really cool

**Comment by hvelarde** [comment]
no use case for this.
