### ISSUE TITLE
Alpha 12 breaks adding a Collection to a Carousel tile

### ISSUE THREAD

**Issue by davilima6** [collective/collective.cover#574]
Steps to reproduce:

1. Add and publish some news items.
2. In Compose view/tab, drag default News collection into a Carousel Tile. It gets green, spinner is briefly displayed but content doesn't get updated. Also noticed there's success (200) for `@@updatetilecontent?tile-type=collective.cover.carousel` when item is dropped.

**Comment by hvelarde** [comment]
@davilima6 I think that never worked; the carousel tile inherits from list tile and you have to drop individual items **with images**: https://github.com/collective/collective.cover/blob/master/src/collective/cover/tiles/carousel.py#L58:L69

**Comment by hvelarde** [comment]
now I understand; @rodfersou please take a look on this later.

**Comment by rodfersou** [comment]
When we drop a collection or a folder into list or caroussel tile, it [adapts the content into a list of items](https://github.com/collective/collective.cover/blob/master/src/collective/cover/tiles/list.py#L389-L410) and never update it's content after that.

Should we review it to update the collection or list automatically?

This could be a new feature that could be turned on or off with a configuration flag.

I just need to keep reference of original object dropped to make this kind of check, and it will work just for tiles configured after this new feature (now we don't keep this reference).

**Comment by hvelarde** [comment]
@rodfersou that's not what @davilima6 is reporting; he says what you state in paragraph 1 is not true for carousels.
