### ISSUE TITLE
Fix RF tests with plone.app.widgets installed

### ISSUE THREAD

**Issue by hvelarde** [collective/collective.cover#580]
Following tests are failing after installing plone.app.widgets:

* [x] Test Collection Tile (`ValueError: Element locator 'xpath=//select[@name="addindex"]' did not match any elements.`)
* [ ] Test Content Body Tile (`ValueError: Element locator 'id=text' did not match any elements.`)
* [ ] Test RichTextTile is Searchable (`ElementNotVisibleException: Message: Element is not currently visible and so may not be interacted with Stacktrace:`)

For more information, see:

* https://travis-ci.org/collective/collective.cover/jobs/103581538
* https://s3-sa-east-1.amazonaws.com/collective-cover/collective/collective.cover/2517/2517.3/parts/test/robot_log.html

**Comment by rodfersou** [comment]
this is causing the problems: [plone.app.widgets 1.8.0 is marking jquery as deprecated](https://github.com/plone/plone.app.widgets/commit/18fc9af6c440800cce7bbbb99c26d17f2564e45b#commitcomment-16768723)

I don't know where our build should get jquery now, if there are other package with jquery to add.
