### ISSUE TITLE
If an exception is thrown in a tile, @@updatetilecontent gives an error 500 and nothing is shown to the user

### ISSUE THREAD

**Issue by idgserpro** [collective/collective.cover#581]
This is difficult to reproduce, since we're using a portuguese tile component in a complex setup that has this behavior, so we'll try to simulate it editing some of collective.cover implementation files to easy the test:

1 - Clone this repository (we tested using commit 6d615de1b3a056a336501e1d61354114c68e8585, before 1.0a13 release);
2 - ```python bootstrap.py``` and ```bin/buildout```;
3 - Create a simple cover and add a simple tile;
4 - Stop Plone;
5 - Edit **src/collective/cover/tiles/basic.py** and add a bunch of

```python
raise Exception("Testing cover handling of tiles brokenness")
```

to all methods (or choose any method that's called in compose view when you select a content to add);

6 - Start Plone again;
7 - You should see:

![selecao_113](https://cloud.githubusercontent.com/assets/8203476/12429962/2af36c3c-bed4-11e5-9d36-d941e7a300c7.png)

This is not a helpful message, but at least the cover isn't broken (similar message when you have a broken portlet);
8 - Go to compose;
9 - Try to add a new item to the basic tile that throwns the exception;
10 - You get:

![selecao_112](https://cloud.githubusercontent.com/assets/8203476/12430008/58cdce9a-bed4-11e5-91aa-a1904d06c6a0.png)

Infinite loading and a 500 Internal Server error, so it's not possible to the user to know if an error occured or if the server is slow. When you click compose again, you see that nothing was saved.

I'm not familiar with this component source code, neither it's javascript implementation, but I think a message should be shown to the user telling an error on the server happened: don't know the best place to show it. Maybe in the place of the loading icon?

**Comment by hvelarde** [comment]
sounds fair to me; @rodfersou let's take a quick look on this

**Comment by idgserpro** [comment]
We can add a `failure: function()` to all ajax calls in https://github.com/collective/collective.cover/blob/adb1a67b27da8657f0b7e099b87dba337c6b04cf/src/collective/cover/static/js/contentchooser.js#L490, or `statusCode` to handle it... but I don't know if there's a better approach. In my opinion, if possible in jquery, a nice thing to do would be a generic handling of all 500 errors.

Since we have `.loading-mask`, we can create an `.error-mask` or something equivalent, that would be used in one of the ideas above to warn the user that something went wrong on the server.

@rodfersou and @hvelarde, ideas?

**Comment by hvelarde** [comment]
+1

**Comment by idgserpro** [comment]
@hvelarde is 1.0a13 towards Plone 5.0? Should I add plone.app.stagingbehavior to packages that depend on collective.cover that will still be installed in 4.3?

**Comment by hvelarde** [comment]
yes, the idea is to fix all compatibility problems, one step at a time, until we get the package running in both versions.

**Comment by rodfersou** [comment]
@idgserpro for me it is fair to add a ``failure`` method and send the error message there.

But there are other places where we need these ``failure`` treatment:

* https://github.com/collective/collective.cover/blob/adb1a67b27da8657f0b7e099b87dba337c6b04cf/src/collective/cover/static/js/contentchooser.js#L490
* https://github.com/collective/collective.cover/blob/adb1a67b27da8657f0b7e099b87dba337c6b04cf/src/collective/cover/static/js/contentchooser.js#L453
* https://github.com/collective/collective.cover/blob/adb1a67b27da8657f0b7e099b87dba337c6b04cf/src/collective/cover/static/js/contentchooser.js#L469
* https://github.com/collective/collective.cover/blob/adb1a67b27da8657f0b7e099b87dba337c6b04cf/src/collective/cover/static/js/compose.js#L71

And not sure if we need this here:
* https://github.com/collective/collective.cover/blob/adb1a67b27da8657f0b7e099b87dba337c6b04cf/src/collective/cover/static/js/compose.js#L30

Need to look with more attention everywhere.

For me the error message could be placed in the same place there is the message "Tile content replaced during the blocks transform." and we think about another kind of mask, or style when there is and error.

@agnogueira could you please think about the style of the error message?
