### ISSUE TITLE
Add option to turn off drag'n'drop among tiles behavior

### ISSUE THREAD

**Issue by davilima6** [collective/collective.cover#592]
It could be interesting to provide a toggle for the new landed feature, at least globally in @@cover-settings. It could be turned off for more conservative teams and places where the publishing dynamics are not as intense as to justify the increase in UI complexity (probability of UI mistakes/accidents), training, support etc.

Other implementation ideas are to have this as a Dexterity behavior, so we add per-object control, or to have it controlled by permission so admins can define which users are allowed with greater power. Since it seems a bit early to know if deployments will really need per-object or per-user control I'd start with the first global suggestion, though.

@agnogueira: what do you think?

**Comment by hvelarde** [comment]
I'm -1 on this; we have no resources for that and it could be time consuming.

@rodfersou, comments?

**Comment by rodfersou** [comment]
I don't think it would be time consuming, we just need to change the [draggable items](https://github.com/collective/collective.cover/blob/master/src%2Fcollective%2Fcover%2Fstatic%2Fjs%2Fcontentchooser.js#L369-L372) back to the way it was before the new feature checking the controlpanel flag.

**Comment by agnogueira** [comment]
-1. Drag & Drop is not a easy to do action. So i think i will not cause so many problemns as you say. This feature will reduce de complexity (less layout changes and less in place content editions)
And you always have the option to use cover + iterate to only edit your cover in a working copy to prevent disasters.

**Comment by hvelarde** [comment]
@davilima6 IMO sites that do not change a lot on the front page should probably be better using Mosaic.
