### ISSUE TITLE
Link integrity is not working

### ISSUE THREAD

**Issue by hvelarde** [collective/collective.cover#604]
A couple of days ago with had an ugly issue with a customer that erased a piece of content referenced by a tile in the front page of their site.

What we have learned until now is the following:

- link integrity is not working so the user had no feedback on implications
- the tile was trying to access the object (already solved in https://github.com/collective/collective.nitf/pull/156)
- plone.app.blocks is aborting the whole transform which leads to a completely broken page (https://github.com/plone/plone.app.blocks/issues/27)

We need to solve the earlier.

**Comment by idgserpro** [comment]
@hvelarde when an object is renamed the tile is updated?

**Comment by hvelarde** [comment]
@idgserpro when you rename an object the UUID remains the same.

**Comment by idgserpro** [comment]
But the title in object it is different than in tile. This is a problem?

**Comment by hvelarde** [comment]
no, that's not a problem but the expected behavior and a common case; you don't want to change the cover object by changing the contents of the referenced objects.
