### ISSUE TITLE
Problem to open layout editor.

### ISSUE THREAD

**Issue by rogeriocdluiz** [collective/collective.cover#616]
I get a error when try open layout editor in any place of site. I receive the error below:

`
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module collective.cover.browser.cover, line 180, in __call__
  Module grokcore.view.components, line 150, in __call__
  Module grokcore.view.components, line 154, in _render_template
  Module five.grok.components, line 130, in render
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
  Module zope.pagetemplate.pagetemplate, line 240, in __call__
  Module zope.tal.talinterpreter, line 271, in __call__
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 888, in do_useMacro
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 954, in do_defineSlot
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 858, in do_defineMacro
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 954, in do_defineSlot
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 946, in do_defineSlot
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 531, in do_optTag_tal
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 742, in do_insertStructure_tal
  Module Products.PageTemplates.Expressions, line 218, in evaluateStructure
  Module zope.tales.tales, line 696, in evaluate
   - URL: /opt/plone437/buildout-cache/eggs/collective.cover-1.0a12-py2.7.egg/collective/cover/browser/templates/layoutedit.pt
   - Line 67, Column 16
   - Expression: <PathExpr standard:u'context/@@group_select'>
   - Names:
      {'args': (),
       'container': <Cover at /intranet/pagina-inicial>,
       'context': <Cover at /intranet/pagina-inicial>,
       'default': <object object at 0x7ff336bc9bc0>,
       'here': <Cover at /intranet/pagina-inicial>,
       'loop': {},
       'nothing': None,
       'options': {},
       'repeat': <Products.PageTemplates.Expressions.SafeMapping object at 0x7ff320601e10>,
       'request': <HTTPRequest, URL=http://plonedev.prdf.mpf.mp.br:8080/intranet/pagina-inicial/layoutedit>,
       'root': <Application at >,
       'static': None,
       'template': <Products.Five.browser.pagetemplatefile.ViewPageTemplateFile object at 0x7ff32356cad0>,
       'traverse_subpath': [],
       'user': <PropertiedUser 'admin'>,
       'view': <collective.cover.browser.cover.LayoutEdit object at 0x7ff3204bd750>,
       'views': <Products.Five.browser.pagetemplatefile.ViewMapper object at 0x7ff320535810>}
  Module zope.tales.expressions, line 217, in __call__
  Module Products.PageTemplates.Expressions, line 155, in _eval
  Module Products.PageTemplates.Expressions, line 117, in render
  Module grokcore.view.components, line 142, in __call__
  Module zope.publisher.publish, line 107, in mapply
   - __traceback_info__: <bound method GroupSelect.update of <collective.cover.layout.GroupSelect object at 0x7ff3204363d0>>
  Module zope.publisher.publish, line 113, in debug_call
  Module collective.cover.layout, line 207, in update
  Module plone.app.vocabularies.security, line 129, in __call__
  Module zope.schema.vocabulary, line 65, in __init__
ValueError: term values must be unique: '01\xbaOficio-1\xbaCrim'

`

-   Plone 4.3.7 (4311)
-   CMF 2.2.9
-   Zope 2.13.23
-   Python 2.7.10 (default, Sep 10 2015, 10:55:40) [GCC 4.3.4 [gcc-4_3-branch revision 152973]]
-   PIL 2.9.0 (Pillow)

**Comment by hvelarde** [comment]
@rogeriocdluiz seems to me the issue is not in collective.cover: you have a duplicated term in some vocabulary; you will need to dig up a little bit.

use something like [Products.PDBDebugMode](http://pypi.python.org/pypi/Products.PDBDebugMode) in your buidlout.

**Comment by hvelarde** [comment]
closed because lack of feedback.
