### ISSUE TITLE
Add Content button is missing

### ISSUE THREAD

**Issue by fulv** [collective/collective.cover#626]
```
Plone 4.3.8
collective.cover 1.1b1
plone.app.tiles = 1.0.1
plone.tiles = 1.5.1
plone.app.drafts = 1.0
plone.app.blocks = 2.2.1
```

I create a Cover with "Layout A".  When I go to the compose tab, there is no "Add Content" button.
For comparison, I created a brand new Plone site on the same Zope instance, and the button is there.

The button is produced by this:

```
<div class="btn" id="contentchooser-content-show-button">Add Content</div>
```

Which is the first child in the `div#content` element.  This `div.btn` is completely missing on the first site.

Any idea what might cause this?

**Comment by hvelarde** [comment]
I have no idea, @fulv, the button must be there; are you upgrading for a previous version?

**Comment by fulv** [comment]
Never mind, I had a js file in portal_skins custom folder that was messing with jQuery, and preventing https://github.com/collective/collective.cover/blob/master/src/collective/cover/static/js/contentchooser.js#L351 from being reached.
