### ISSUE TITLE
br data-mce-bogus="1" added on transform when link inserted in Rich Text tile

### ISSUE THREAD

**Issue by BarbaraHarris** [collective/collective.cover#627]
Before link added:

```html
<div class="cover-richtext-tile tile-content">
<p>Link 1</p>
<p>Link 2</p>
<p>Text</p>
</div>
After:
<div class="cover-richtext-tile tile-content">
<p>
<a class="external-link" href="http://www.bbc.co.uk" data-mce-href="http://www.bbc.co.uk" title="" target="_self" style="">Link 1</a>
<br data-mce-bogus="1">
</p>
<p>Link 2</p>
<p>Text</p>
</div>

```
Only appears in browser not in tile. Is this correct behaviour?

**Comment by BarbaraHarris** [comment]
[data-mce-bogusEG.txt](https://github.com/collective/collective.cover/files/300917/data-mce-bogusEG.txt)
previous example cleaned up in GitHub

**Comment by hvelarde** [comment]
I think I didn't understand your problem; could you please edit the issue describing what are you doing (step by step), what do you expect and what are you getting?

**Comment by BarbaraHarris** [comment]
On a Plone 4.3.6 site, when I edit a Rich Text tile in the compose tab of a cover, if I add a link, using the TinyMCE Insert/Edit link function, the code looks like linkHTMLversion1.txt (attached)
When I view the source in a browser, the code looks like linkHTMLversion2.txt (also attached).
The br data-mce-bogus="1" tag is adversely affecting our styling, especially when adding links to list items.  This extra data-mce code is only being rendered in the browser when links are added to Rich Text cover tiles, not ordinary Plone pages.  The only reference I've found to this code is that it's something to do with inline access to empty text fields, which is not the case here.  The code is rendered in various versions of Firefox, Chrome and IE.  I just want to know if it's valid , in whcih case we can style around it, or if it's a result of some JavaScript configuration we've either go wrong or mis-configured.  Any pointer in the right direction would be appreciated. 


[linkHTMLversion2.txt](https://github.com/collective/collective.cover/files/302276/linkHTMLversion2.txt)


[linkHTMLversion1.txt](https://github.com/collective/collective.cover/files/302268/linkHTMLversion1.txt)

**Comment by BarbaraHarris** [comment]
I should also have listed the (possibly) relevant product installations on the site:
Plone JQuery Integration 1.7.2
Plone JQuery Tools Integration 1.5.7
Tiles support 1.0.1
collective.cover 1.0a11
collective.js.cycle2 1.0b1
collective.js.galleria 1.2.5
covertile.cycle2: A Cycle2 based carousel tile for collective.cover 	1.0a1
jQuery UI 1.8.16.9

**Comment by BarbaraHarris** [comment]
I've just discoverd that the tile text format is defaulting to text/html.  If I change it to text/x-plone-outputfilters-html the problem goes away, but so does the TinyMCE WYSIWYG UI.
