### ISSUE TITLE
Can't edit basic tile with Dexterity-based content types

### ISSUE THREAD

**Issue by hvelarde** [collective/collective.cover#637]
Plone 4.3.10 with plone.app.contenttypes 1.1.1 installed:
- upload an Image or create a News Item with an image
- drop the item in a basic tile
- edit the tile
- save it

the following validation error is shown (`Wrong contained type`):

![selection_073](https://cloud.githubusercontent.com/assets/341393/17038999/bd93ae50-4f6e-11e6-85f0-bb54d3235638.png)

this was not happening before with Plone 4.3.9.

**Comment by hvelarde** [comment]
@jensens @thet any hints?

**Comment by jensens** [comment]
@hvelarde sorry, I have no clue what's going on there.

**Comment by davilima6** [comment]
@hvelarde: no traceback and nothing else in the console?

**Comment by hvelarde** [comment]
@davilima6 nothing; seems some invariant or validator in the image widget.

**Comment by rodfersou** [comment]
This validation looks to be into [zope.schema._field.py file](https://github.com/zopefoundation/zope.schema/search?utf8=%E2%9C%93&q=WrongContainedType)

**Comment by hvelarde** [comment]
I found the problem but I have no idea how to fix it: the value of the `contentType` property of the `NamedBlobImage` field is `unicode` instead of `str`

```
> /home/hvelarde/.buildout/eggs/zope.schema-4.2.2-py2.7.egg/zope/schema/_field.py(586)_validate()
-> raise WrongContainedType(errors, self.__name__)
(Pdb) errors
[WrongType(u'image/jpeg', <type 'str'>, 'contentType')]
(Pdb) self.schema
<InterfaceClass plone.namedfile.interfaces.INamedBlobImage>
(Pdb) value
<plone.namedfile.file.NamedBlobImage object at 0x7f48ec341848>
(Pdb) value.contentType
u'image/jpeg'
(Pdb) type(value.contentType)
<type 'unicode'>
```

I have no idea of what's the cause of this bug.

@idgserpro can you confirm if this happens on the IDGB project, please?

**Comment by hvelarde** [comment]
according to @datakurre Dexterity and z3c.form converts all form data into `unicode` so maybe that is causing this issue.

we need to check if this fixes it: https://github.com/plone/plone.app.tiles/pull/10/files

**Comment by rodfersou** [comment]
It looks like this is the same bug https://community.plone.org/t/migration-collective-jsonify-news-item-images-lead-image-wrong-contained-type/1544

**Comment by rodfersou** [comment]
@hvelarde @datakurre the fixes done at **p.a.tiles** raises an exception with **c.cover** tiles:

```python
2016-12-22 11:52:05 ERROR Zope.SiteErrorLog 1482414725.910.636643873446 http://localhost:8080/Plone/capa/@@updatetilecontent
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module Products.PDBDebugMode.runcall, line 70, in pdb_runcall
  Module ZPublisher.Publish, line 48, in call_object
  Module collective.cover.browser.compose, line 57, in __call__
  Module collective.cover.browser.compose, line 52, in render
  Module collective.cover.tiles.basic, line 122, in populate_with_object
  Module z3c.form.form, line 37, in applyChanges
AttributeError: 'BasicTile' object has no attribute 'fields'
/home/rodfersou/.anyenv/envs/pyenv/versions/2.7.12/envs/collective.cover/lib/python2.7/site-packages/IPython/core/debugger.py:238: DeprecationWarning: The `color_scheme` argument is deprecated since version 5.1
  DeprecationWarning)
> /home/rodfersou/.projects/cache/eggs/z3c.form-3.2.9-py2.7.egg/z3c/form/form.py(37)applyChanges()
     35 def applyChanges(form, content, data):
     36     changes = {}
---> 37     for name, field in form.fields.items():
     38         # If the field is not in the data, then go on to the next one
     39         try:
```

**Comment by rodfersou** [comment]
at my PR I just convert back `image.contentType` to `string`

**Comment by rodfersou** [comment]
it looks like the bug was introduced in this commit by @thet 

https://github.com/plone/plone.namedfile/commit/33df023d09c3d18df14f7f93feeca2ba5bf19c88#diff-03f29bbadcdf640341c9061de5a07dccR299

When we scale the image, **contentType** attribute of NamedBlobImage object becomes **unicode** when it should be **str**

**Comment by hvelarde** [comment]
@rodfersou great! can you fix it upstream then?

**Comment by rodfersou** [comment]
how did you test it? here it works

**Comment by datakurre** [comment]
@rodfersou Great work!

**Comment by jensens** [comment]
@rodfersou bug hunting at its best!

**Comment by hvelarde** [comment]
wow, I tested again and you were totally right; the problem was I was testing with an image created prior to the patch... that means now we have a huge issue: all scales in the portal must have to be checked using an upgrade step because the `contentType` attribute will be `unicode` and we'll need to update them to be `str`.

**Comment by thet** [comment]
Should be fixed via:
https://github.com/plone/plone.namedfile/pull/41
and
https://github.com/plone/plone.namedfile/pull/45

@hvelarde if an upgrade step is really needed, talk to me.
