### ISSUE TITLE
TypeError accessing Compose view in Plone 5

### ISSUE THREAD

**Issue by hvelarde** [collective/collective.cover#641]
Plone 5.0.5 with collective.cover installed from master branch (1.2b2, unreleased).

After creating a cover object with Layout A, try to access the Compose tab; the following JavaScript error is shown in the console:

```javascript
21:37:23.653 TypeError: $(...).prepOverlay is not a function
<anonymous>compose.js:99
m.Callbacks/j()default.js:2
m.Callbacks/k.fireWith()default.js:2
.ready()default.js:2
J()default.js:2
1compose.js:99:3
```

**Comment by rodfersou** [comment]
``prepOverlay`` is a method added from ``plone.app.jquerytools`` and is the default way to create overlays in plone 4.x AFAIK.

This issue means replace ``plone.app.jquerytools`` with other kind of overlay?
