### ISSUE TITLE
Broken layouts in Plone 5

### ISSUE THREAD

**Issue by hvelarde** [collective/collective.cover#652]
Plone 5.0.5 with collective.cover installed from master branch (1.2b2, unreleased).

Create a cover object with Layout A, access the Layout tab and you see a broken layout:

![screen shot 2016-08-18 at 12 27 16](https://cloud.githubusercontent.com/assets/341393/17779868/9be13fca-653f-11e6-91e1-9ac5777bac6f.png)

This happens because the included layouts were made using Deco grid system (16 columns) and the default grid system in Plone 5 is Bootstrap 3 (12 columns).

**Comment by rodfersou** [comment]
The default layouts are defined [in the registry](https://github.com/collective/collective.cover/blob/master/src/collective/cover/profiles/default/registry.xml#L13-L16) today.
And default grid system in [config.py](https://github.com/collective/collective.cover/blob/master/src/collective/cover/config.py#L36).
I think it is time to move on and change the default grid system for Plone 4.3 to Bootstrap 3 and update the default layouts in the registry.

**Comment by hvelarde** [comment]
we'll keep different grid systems for different Plone version; we can get rid of the included default layouts as I think nobody use them anyway.
