### ISSUE TITLE
Can't configure tile in Plone 5

### ISSUE THREAD

**Issue by hvelarde** [collective/collective.cover#667]
Plone 5.0.6 with collective.cover from the master branch.
- add a cover object with an empty layout
- add a basic tile
- try to configure the tile

the following error is shown in the console:

``` javascript'
22:31:11.798 TypeError: $(...).modal is not a function
LayoutManager/<.tile_config_manager/<()layout_edit.js:528
m.event.dispatch()default.js:4
b.dispatch()default.js:2492
m.event.add/r.handle()default.js:4
1layout_edit.js:528:11
```

**Comment by rodfersou** [comment]
closed in https://github.com/collective/collective.cover/pull/654
