### ISSUE TITLE
Do we really need https://raw.github.com/plone/plone.app.robotframework/master/versions.cfg in buildout.cfg's extend section?

### ISSUE THREAD

**Issue by idgserpro** [collective/collective.cover#672]
We already extend http://dist.plone.org/release/4.3-latest/versions.cfg which has a pretty decent pinning for robots:

```cfg
# Robot Testing
plone.app.robotframework = 1.0
robotframework = 3.0
robotframework-debuglibrary = 0.4
robotframework-ride = 1.5.2.1
robotframework-selenium2library = 1.7.4
robotframework-selenium2screenshots = 0.7.0
robotsuite = 1.7.0
selenium = 2.53.5
sphinx-rtd-theme = 0.1.5
sphinxcontrib-robotframework = 0.5.1
```

Why exactly do we need to extend https://raw.github.com/plone/plone.app.robotframework/master/versions.cfg again?

**Comment by hvelarde** [comment]
try to remove it and see what happens; we will probably need to maintain a pinning for Selenium.

**Comment by idgserpro** [comment]
https://travis-ci.org/collective/collective.cover/builds/170107306

In 4.2: WebDriverException: Message: 'geckodriver' executable needs to be in PATH. 

In 4.3 with jquery: AssertionError: Element 'xpath=.//a[@class='calendar-tile-next'][@data-month='11'][@data-year='2016']' did not appear in 30 seconds

**Comment by hvelarde** [comment]
ois dois parecem Mandelbugs...

**Comment by idgserpro** [comment]
The first one is because the 4.2 job it's downloading selenium >= 3, as we can see in https://s3.amazonaws.com/archive.travis-ci.org/jobs/170107307/log.txt, and this error is [supposed to happen](https://github.com/robotframework/Selenium2Library/issues/644#issuecomment-243887620) anyway when we have this selenium version.

It downloads selenium 3 because http://dist.plone.org/release/4.2-latest/versions.cfg doesn't pin any of robots infrastructure, so it seems that, at least for 4.2, we still need to use https://raw.github.com/plone/plone.app.robotframework/master/versions.cfg. Check https://github.com/collective/collective.cover/commit/ebaf313b117a9ac03fd71c88024a78ca8f90440a and the build https://travis-ci.org/collective/collective.cover/builds/170460367, it fixes the build. The second one really seems as a Mandelbug since the whole build is ok...

**Comment by idgserpro** [comment]
IMHO, I think we should pin just in 4.2 with the justification we gave in https://github.com/collective/collective.cover/blob/ebaf313b117a9ac03fd71c88024a78ca8f90440a/versions-4.2.x.cfg. What do you think? We could make a PR from the branch and close this issue.

**Comment by idgserpro** [comment]
Done in https://github.com/collective/collective.cover/pull/679
