### ISSUE TITLE
Can't compose a cover in Plone 5.0.6

### ISSUE THREAD

**Issue by rafaeltcc** [collective/collective.cover#678]
Vanilla Plone 5.0.6

I create a cover. As soon as I hit compose (no matter the layout), I get the following error:

Traceback (innermost last):

    Module ZPublisher.Publish, line 138, in publish
    Module ZPublisher.mapply, line 77, in mapply
    Module ZPublisher.Publish, line 48, in call_object
    Module collective.cover.browser.compose, line 28, in __call__
    Module Products.Five.browser.pagetemplatefile, line 125, in __call__
    Module Products.Five.browser.pagetemplatefile, line 59, in __call__
    Module zope.pagetemplate.pagetemplate, line 132, in pt_render
    Module five.pt.engine, line 98, in __call__
    Module z3c.pt.pagetemplate, line 163, in render
    Module chameleon.zpt.template, line 261, in render
    Module chameleon.template, line 171, in render
    Module 8bd604fa6c804b17dd3803916a992a86.py, line 293, in render
    Module f866a36a6fd527e96b45b1f5491375bc.py, line 1223, in render_master
    Module f866a36a6fd527e96b45b1f5491375bc.py, line 458, in render_content
    Module 8bd604fa6c804b17dd3803916a992a86.py, line 258, in __fill_main
    Module five.pt.expressions, line 161, in __call__
    Module collective.cover.browser.contentchooser, line 38, in __call__
    Module zope.browserpage.viewpagetemplatefile, line 83, in __call__
    Module zope.browserpage.viewpagetemplatefile, line 51, in __call__
    Module zope.pagetemplate.pagetemplate, line 132, in pt_render
    Module five.pt.engine, line 98, in __call__
    Module z3c.pt.pagetemplate, line 163, in render
    Module chameleon.zpt.template, line 261, in render
    Module chameleon.template, line 171, in render
    Module 1e962db79ab6cf5a9706f42a3c553e2d.py, line 338, in render
    Module five.pt.expressions, line 161, in __call__
    Module collective.cover.browser.contentchooser, line 94, in __call__
    Module collective.cover.browser.contentchooser, line 90, in render
    Module zope.browserpage.viewpagetemplatefile, line 83, in __call__
    Module zope.browserpage.viewpagetemplatefile, line 51, in __call__
    Module zope.pagetemplate.pagetemplate, line 132, in pt_render
    Module five.pt.engine, line 98, in __call__
    Module z3c.pt.pagetemplate, line 163, in render
    Module chameleon.zpt.template, line 261, in render
    Module chameleon.template, line 191, in render
    Module chameleon.template, line 171, in render
    Module 233e62be11ca909e09ecc68d9e07589e.py, line 259, in render
    Module five.pt.expressions, line 154, in __call__
    Module five.pt.expressions, line 126, in traverse
    Module zope.traversing.adapters, line 136, in traversePathElement
    __traceback_info__: ({'no_display': False, 'getURL': 'http://dev.pcml.org.br/Plone2/front-page', 'show_children': False, 'normalized_review_state': 'published', 'normalized_id': 'front-page', 'UID': '9a0299cb11574b60a918eaeef0b97ece', 'Title': 'Welcome to Plone', 'absolute_url': 'http://dev.pcml.org.br/Plone2/front-page', 'portal_type': 'Document', 'Creator': 'admin', 'useRemoteUrl': False, 'creation_date': '2016-10-26T14:15:54-02:00', 'item': <Products.ZCatalog.Catalog.mybrains object at 0x76face8>, 'getRemoteUrl': Missing.Value, 'link_remote': Missing.Value, 'path': '/Plone2/front-page', 'review_state': 'published', 'normalized_portal_type': 'document', 'id': 'front-page', 'Description': 'Congratulations! You have successfully installed Plone.'}, 'item_icon')
    Module zope.traversing.adapters, line 50, in traverse
    __traceback_info__: ({'no_display': False, 'getURL': 'http://dev.pcml.org.br/Plone2/front-page', 'show_children': False, 'normalized_review_state': 'published', 'normalized_id': 'front-page', 'UID': '9a0299cb11574b60a918eaeef0b97ece', 'Title': 'Welcome to Plone', 'absolute_url': 'http://dev.pcml.org.br/Plone2/front-page', 'portal_type': 'Document', 'Creator': 'admin', 'useRemoteUrl': False, 'creation_date': '2016-10-26T14:15:54-02:00', 'item': <Products.ZCatalog.Catalog.mybrains object at 0x76face8>, 'getRemoteUrl': Missing.Value, 'link_remote': Missing.Value, 'path': '/Plone2/front-page', 'review_state': 'published', 'normalized_portal_type': 'document', 'id': 'front-page', 'Description': 'Congratulations! You have successfully installed Plone.'}, 'item_icon', ())

LocationError: ({'no_display': False, 'getURL': 'http://dev.pcml.org.br/Plone2/front-page', 'show_children': False, 'normalized_review_state': 'published', 'normalized_id': 'front-page', 'UID': '9a0299cb11574b60a918eaeef0b97ece', 'Title': 'Welcome to Plone', 'absolute_url': 'http://dev.pcml.org.br/Plone2/front-page', 'portal_type': 'Document', 'Creator': 'admin', 'useRemoteUrl': False, 'creation_date': '2016-10-26T14:15:54-02:00', 'item': <Products.ZCatalog.Catalog.mybrains object at 0x76face8>, 'getRemoteUrl': Missing.Value, 'link_remote': Missing.Value, 'path': '/Plone2/front-page', 'review_state': 'published', 'normalized_portal_type': 'document', 'id': 'front-page', 'Description': 'Congratulations! You have successfully installed Plone.'}, 'item_icon')

 - Expression: "context/@@select-content-contentchooser"
 - Filename:   ... -py2.7.egg/collective/cover/browser/templates/compose.pt
 - Location:   (line 36: col 31)
 - Source:     ... ce="structure context/@@select-content-contentchooser" />
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 - Expression: "node/item_icon"
 - Filename:   ... .7.egg/collective/cover/browser/templates/search_list.pt
 - Location:   (line 13: col 33)
 - Source:     item_icon node/item_icon;
                         ^^^^^^^^^^^^^^
 - Arguments:  node: {...} (20)
               repeat: {...} (0)
               context: <ImplicitAcquisitionWrapper teste-1 at 0x8a97410>
               views: <ViewMapper - at 0x7f5329880d90>
               modules: <TraversableModuleImporter - at 0x39f2690>
               args: <tuple - at 0x7f533d039050>
               nothing: <NoneType - at 0x895a60>
               children: <list - at 0x7f5328b53e60>
               target_language: <NoneType - at 0x895a60>
               item_url: http://dev.pcml.org.br/Plone2/front-page
               uuid: 9a0299cb11574b60a918eaeef0b97ece
               level: 1
               default: <object - at 0x7f533cfa4510>
               translate: <function translate at 0x7f532897cde8>
               request: <instance - at 0x7f5328b743f8>
               wrapped_repeat: {...} (1)
               options: {...} (0)
               loop: {...} (1)
               template: <ViewPageTemplateFile - at 0x9dd4450>
               view: <ContentSearch content-search at 0x7f53298805d0>
               type: Document
               item_token: /Plone2/front-page
               portal_path: /Plone2

**Comment by hvelarde** [comment]
package is not compatible with Plone 5; use master branch as your own risk.
