### ISSUE TITLE
Remove unnecessary dependency on plone.app.relationfield

### ISSUE THREAD

**Issue by alecghica** [collective/collective.cover#684]
Right now _collective.cover_ depends on _plone.app.relationfield_ which can easily made optional. This (unused?) dependency brings more problems than benefits and can be added independently if needed.

Problem is that _plone.app.relationfield_ is dependent of _plone.app.intid_ which, on install, loops through the whole catalog and does a _getObject_ on each brain:

* https://github.com/plone/plone.app.intid/blob/master/plone/app/intid/setuphandlers.py#L24

... this operation will never succeed if you have a medium or large database already, with ten of thousand of objects/brains for example and you will never be able to install the _collective.cover_.

Removing dependency of _plone.app.relationfield_ can be done easily by removing the followings:

* https://github.com/collective/collective.cover/blob/master/src/collective/cover/profiles/default/metadata.xml#L10
* https://github.com/collective/collective.cover/blob/master/src/collective/cover/profiles/default/types/collective.cover.content.xml#L25
* https://github.com/collective/collective.cover/blob/master/src/collective/cover/configure.zcml#L14

**Comment by hvelarde** [comment]
a PR is highly appreciated; plaase document what to do on upgrades to not break current installations, the same we did with other hard dependencies we have been removing in the last months.

**Comment by alecghica** [comment]
I won't have the time for this in the near future so anyone interested in adding a pull request for this is welcomed.
