### ISSUE TITLE
Carousel tile does not respect image size set in layout configuration

### ISSUE THREAD

**Issue by rafaeltcc** [collective/collective.cover#692]
Plone 4.3.11 vanilla. Only product installed is latest version of collective.cover.

In the layout configuration for the CarouseI Tile the image size is at its default value mini 200:200. When I drag and drop a news in the compose tab the image grows larger, fulfilling all the avaiable space. The only workaround I could find to have a smaller image is to add another column and restrain the avaiable space.

I also noted an empty line in the Carousel tile configuration (see image below). There is just the eye on it, and nothing written. I did not open a new issue to this because it may be related.

![carrousel](https://cloud.githubusercontent.com/assets/3977779/21101906/9990d3a6-c062-11e6-9aa0-1888034f60c7.jpg)

**Comment by hvelarde** [comment]
this is not a bug, but an expected behavior: the carousel tile expands the images to fit the whole area to support responsiveness; the setting is just there to take care of the bigger resolution to be used.

**Comment by rafaeltcc** [comment]
And what about the empty line below the Data with just an eye (shown in the picture)? Should I open a bug for that?

**Comment by hvelarde** [comment]
yes, that's a different issue; it may seem a lot of bureaucracy to you, but is the only way to keep things organized.
