### ISSUE TITLE
Use sudo: required in .travis.yml

### ISSUE THREAD

**Issue by idgserpro** [collective/collective.cover#703]
```collective.cover``` has several robot tests. Robot tests consume a lot of memory. According to [this documentation](https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments), using ```sudo: required```, we have more memory. Maybe that will decrease the Mandelbugs.

**Comment by hvelarde** [comment]
and then they will take eons to finish; I'm against this.

**Comment by idgserpro** [comment]
@hvelarde tests of the cover is already take too long. Taking an extra minute will not make so much difference. If decrease the Mandelbugs, I think it's worth it.

Then I'll do a PR to check.

**Comment by hvelarde** [comment]
it's not going to take one more minute but much more; when you set `sudo: true` you no longer use caching.

we better fix the failing tests.

**Comment by idgserpro** [comment]
@hvelarde in fact, the cache works with ```sudo: true```. See:

https://github.com/plone/bobtemplates.plone/issues/193#issuecomment-277763853

**Comment by hvelarde** [comment]
awesome! if we're not loosing the caching feature I'm ok with changing that; please open a PR to test it.
