### ISSUE TITLE
In Plone 4 all tiles can be dragged in the view template (have ui-draggable/droppable)

### ISSUE THREAD

**Issue by fredvd** [collective/collective.cover#710]
After installing 1.4b1 in a custom project and verifying the same behaviour in the collective.cover buildout: all outer tile divs now have ui-draggable and ui-droppable classes. 

When you view a cover page you can now no longer select any text inside a cover as you activate the draggable behaviour and visitors can drag around tiles around the page (that will snap back as soon they release the mouse button).

A quick search through the collective.cover code doesn't show any ui-draggable/droppable in templates or javascript, so I suspect this regression is coming from a higher pinned support package, plone.app.tiles or plone.app.blocks .

**Comment by hvelarde** [comment]
CC @rodfersou @datakurre

**Comment by fredvd** [comment]
Digging a bit more in this, I cannot find draggable/droppable strings in p.a.blocks/p.a.tiles either and disabling javascript in the browser removes the classes from the div, so there is some javascript running that adds these classes on the client. Still haven't found the cause though.

**Comment by fredvd** [comment]
It's not caused by plone.app.blocks/tiles, sorry for the confusion.

When I disable contenchooser.js in portal_javascript it stops ui-draggable/ui-droppable being added on the tiles in view mode. contentchooser.js is always loaded, not only in compose mode. Was this maybe changed when the contenchooser.js is activated? 

@rodfersou @hvelarde contenchooser.js hasn't changed much since end 2015 (where drag/drop between tiles was added, but not the tiles themselves). I've been looking for obvious changes but cannot find them. Any ideas?

**Comment by fredvd** [comment]
https://github.com/collective/collective.cover/blob/master/src/collective/cover/static/js/contentchooser.js#L372 causes all tiles to get a ui-draggable class. @rodfersou Why is this necessary on tile level when the drag-drop functionality should be for (list) elements between tiles? 

Still strange, because I cannot remember seeing this bug since switching to 1.4b1, so maybe some other change is triggering this.

**Comment by hvelarde** [comment]
that is related with the drag-and-drop among tiles feature added in #487; I have no idea if that is indeed needed.

**Comment by fredvd** [comment]
@rodersou @hvelarde Yes, this solves the issue, thank you very much!
