### ISSUE TITLE
Uncaught TypeError: $(...).tabs is not a function

### ISSUE THREAD

**Issue by zopyx** [collective/collective.cover#718]
Latest Plone 5.1 + collective.cover 1.4b1 gives the following error as soon as I click on "Compose"

plone-legacy-compiled.js:19 Uncaught TypeError: $(...).tabs is not a function
    at contentchooserMaker (plone-legacy-compiled.js:19)
    at HTMLDocument.<anonymous> (plone-legacy-compiled.js:19)
    at j (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at Function.ready (jquery.min.js:2)
    at HTMLDocument.J (jquery.min.js:2)

**Comment by zopyx** [comment]
The problem is independent of the following version pins:
```

[versions]
collective.js.jqueryui = 1.8.16.9
plone.app.jquery = 1.7.2
plone.app.jquerytools = 1.5.7
plone.app.z3cform = 0.6.3
plone.directives.form = 1.1
```

**Comment by hvelarde** [comment]
this package is still not compatible with Plone 5; I'm adding this issue to the list of things that need to be fixed, but I have to warn you that I have still no interest on fix this as we don't have a use case and I think we should wait until the RR is fixed.

**Comment by rodfersou** [comment]
here we can use as base this referenced PR, but keep the tabs function just for plone 4.x
