### ISSUE TITLE
Should plone.app.jquery be 1.7.2.1 instead of 1.7.2 in versions-4.3.x.cfg?

### ISSUE THREAD

**Issue by idgserpro** [collective/collective.cover#731]
In http://dist.plone.org/release/4.3.9/versions.cfg and http://dist.plone.org/release/4.3-latest/versions.cfg we have 1.7.2.1, any reason for being 1.7.2 in https://github.com/collective/collective.cover/blob/bac226c9b31abcb7d469a2610c9267547f93b8a7/versions-4.3.x.cfg#L26? If we decide to change it, we need to change https://github.com/collective/collective.cover/blob/bac226c9b31abcb7d469a2610c9267547f93b8a7/.travis.yml#L29 as well.

**Comment by hvelarde** [comment]
I was aware of this, but didn't want to change too many things on a previous PR.
