### ISSUE TITLE
Contentchooser calls jsonbytype on wrong url for portal root

### ISSUE THREAD

**Issue by mauritsvanrees** [collective/collective.cover#733]
Tested on current master branch (and it seems to have been there at least since 2012).
Steps:

- Create a cover
- Go to the compose page
- Click on 'Add content' (the contentchooser)
- Click on 'Content tree'
- Navigate to a folder, for example news. This uses javascript to call `http://127.0.0.1:8080/Plone/news/@@jsonbytype`
- In the breadcrumbs of the content tree, click on the portal root. This uses javascript to call `/Plone/@@jsonbytype`

The last step works fine locally, but fails with a 404 on a live site. This is because the resulting full url is something like `http://my.domain/Plone/@@jsonbytype`, and `http://my.domain` usually directly points to the Plone site, and this does not have a folder `Plone` inside it.

This only happens for the root, all other folders in the breadcrumbs use the full url, but the root uses the physical path.
Seems easy to fix by using the full url for the root as well. I will make a pull request.

**Comment by idgserpro** [comment]
Solved in https://github.com/collective/collective.cover/pull/734.
