### ISSUE TITLE
Problem on Upgrade collective.cover.upgrades.v13

### ISSUE THREAD

**Issue by makelli** [collective/collective.cover#741]
I cant execute the upgrade step v13(Update referencesUpdate references used for link integrity checking. | (12 → 13)) on version 1.1.b1 because i have tiles with same id:

[{'type': u'collective.cover.embed', 'id': u'd23df2d155204a39bb185961c70fee56'}, 
 {'type': u'standaloneheader', 'id':       u'd23df2d155204a39bb185961c70fee56'}]

How do i proceed to complete the upgrade ?

**Comment by hvelarde** [comment]
you have to upgrade to 1.2b1 instead; check the changelog:

> * Handle AssertionError on upgrade step to profile 13 to avoid failures when a cover object has duplicated tiles on it. Now, an error message will be logged and the object will be skipped; you must manually remove the duplicated tiles (closes #619). [hvelarde]

**Comment by makelli** [comment]
How can i find these objects to remove ?

**Comment by hvelarde** [comment]
I think is safe to upgrade to 1.2b1, anyway, you can check the upgrade step code in https://github.com/collective/collective.cover/pull/620/files. once you find the guilty tiles, you must replace them manually to get a new UUID.

let's rise this issue to @idgserpro; I think is important to upgrade to 1.2b1 as people has been running bugged versions of collective.cover for too much time and is pretty obvious the problem you're facing will be found by others.

**Comment by idgserpro** [comment]
In this case, we suggest the user to:

- Either edit the upgradeStep in production server with the fix in 1.2b1 to migrate these objects;
- Delete the objects that are giving this problem (do a portal_catalog in a Python Script in ZMI to try to identify which object has these ids);

Next IDG release will have a collective.cover update, > 1.2b1, so this fix will be available.
