### ISSUE TITLE
Additional TinyMCE formats not showing in RichText Tile visual editor

### ISSUE THREAD

**Issue by abosio** [collective/collective.cover#743]
- Plone 5.1b3 (5106)
- collective.cover 1.6b1

Out of the box, Plone's TinyMCE editor has some additional styles in the Formats menu, these do not show up in the TinyMCE instance of a Rich Text Tile in Compose mode in the Edit overlay. Additional custom styles added by my theme product also do not appear.

Steps to Reproduce:
1. Create a clean Plone 5 site and install collective.cover
2. Add a Page, observe the styles available in the Formats menu.
3. Add a Cover, with a Rich Text Tile in the Layout and Save.
4. Click Compose and Edit the Rich Text Tile.
5. Observe the styles available in the Formats menu.

![tinymce](https://user-images.githubusercontent.com/2130406/29053914-dd68c682-7bc0-11e7-969f-73d8da157345.jpg)

**Comment by hvelarde** [comment]
thank you! let us know if you can help on fixing this.

**Comment by abosio** [comment]
I was trying to see why that would be happening. Let me know if you have
any ideas that would point me in the right direction.

**Comment by hvelarde** [comment]
I'm sorry, we're still not using collective.cover in Plone 5.

**Comment by idgserpro** [comment]
Both use `from plone.app.textfield import RichText`. https://github.com/collective/collective.cover/blob/1.6b1/src/collective/cover/tiles/richtext.py#L11, https://github.com/plone/plone.app.contenttypes/blob/1.3.0/plone/app/contenttypes/behaviors/richtext.py#L3, although the behavior uses `from plone.app.z3cform.widget import RichTextFieldWidget` as well.

Don't know how to dig in this z3c.form rabbit hole, rs.

**Comment by rileydog** [comment]
The same issue is with Mosaic:  the full list of pull downs isn't available when adding a rich text edit tile.  So I don't think it is a collective cover issue.

**Comment by hvelarde** [comment]
@datakurre are you aware of this? is there any issue opened upstream?

**Comment by datakurre** [comment]
No, I’m not aware. It has worked for us with Mosaic, but we are still on some 5.1a.

**Comment by hvelarde** [comment]
@abosio BTW, may I ask how are you running collective.cover in Plone 5.1b3? AFAIK the package JS is broken for that version (#642).

**Comment by abosio** [comment]
@hvelarde So far we have only noticed a few of other issues in addition to this one, but they are not showstoppers. I will report those as well if I don't see them here. It is mostly working for us and we are putting it in production soon.

We _are_ running a local version of the package where @cdw9 fixed one problem but I don't remember which one it was.

**Comment by hvelarde** [comment]
thanks! please check the issue I mentioned above as it contains a list of knows issues of this package under Plone 5.

also, please open a new branch and PR to address the issues here so we can fix them here.

**Comment by scmos** [comment]
I just reviewed the issue and I see that there is no problem for plone 5.1.5 and collective.cover 2.2.0
![image](https://user-images.githubusercontent.com/29259948/66424242-e1ab1380-e9d2-11e9-8f3d-246fee95e295.png)

Evidence
![image](https://user-images.githubusercontent.com/29259948/66424423-39497f00-e9d3-11e9-859e-32d7b656aa34.png)
