### ISSUE TITLE
resourcecollective.covercontentchooser listed as "potentially suspicious"

### ISSUE THREAD

**Issue by djowett** [collective/collective.cover#750]
by some scanning software.  I know it doesn't know what it's talking about, but could we at least make contentchooser for authenticated only?

It's this line causing alarm:
data:image/vnd.microsoft.icon;base64,AAACAAEAICACAAcABQAwAQAAFgAAACgAAAAgAAAAQAAAAAEAAQAAAAAAAAEAAAA']] 

vnd.microsoft.icon is not especially current according to this.... https://stackoverflow.com/a/28300054/3046069

**Comment by hvelarde** [comment]
I agree; we're quite busy right now and this seems easy to fix PR anyone? ;-)

**Comment by hvelarde** [comment]
I'm going to make a quick fix of the MIME type as @idgserpro is waiting for a release.

**Comment by idgserpro** [comment]
Thanks @hvelarde! @djowett would you mind creating a new issue to remember to refactor the CSS/JS like [@hvelarde said](https://github.com/collective/collective.cover/issues/750#issuecomment-326635642)? The PR https://github.com/collective/collective.cover/pull/751/files is going to close this issue.

**Comment by djowett** [comment]
@idgserpro done - IIUYC
