### ISSUE TITLE
Problem to render the pool tile 

### ISSUE THREAD

**Issue by makelli** [collective/collective.cover#754]
I can't render a pool tile on cover. On the tab "Compose" appears the message "there was an error while redering this tile". And when I try to load a pool object :

```
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module grokcore.view.components, line 151, in __call__
  Module zope.publisher.publish, line 107, in mapply
   - __traceback_info__: <bound method UpdateTileContent.render of <collective.cover.browser.cover.UpdateTileContent object at 0x7f5caacb7210>>
  Module zope.publisher.publish, line 113, in debug_call
  Module collective.cover.browser.cover, line 221, in render
  Module plone.tiles.esi, line 72, in __call__
  Module plone.tiles.esi, line 54, in render
TypeError: 'NotImplementedType' object is not callable
```

**Comment by idgserpro** [comment]
You can give us a screenshot of the tile that you are using that is giving you problems if you don't know the name of it in english.

**Comment by hvelarde** [comment]
@makelli check the version of plone.tiles you're using; it has to be the recommended version in collective.cover's README file.

see: https://community.plone.org/t/response-gone-when-using-plone-memoize-on-tiles/3754

if problem persists open a new issue in [collective.polls issue tracker](https://github.com/collective/collective.polls/issues).
