### ISSUE TITLE
Robot Framework tests fail with Plone > 4.3.11

### ISSUE THREAD

**Issue by hvelarde** [collective/collective.cover#759]
After upgrading to Plone 4.3.12 all Robot Framework tests started failing as hown in the following screenshot:

![selenium-screenshot-1](https://user-images.githubusercontent.com/341393/31778831-67a593aa-b4d0-11e7-96a2-dfcdf44f7bd2.png)

as it can be seen, there's a new required field being shown in the form that normally doesn't appear; this field came from a [XML schema](https://github.com/collective/collective.cover/blob/1.6b2/src/collective/cover/models/cover.xml#L19-L26) like this:

```xml
<field name="cover_layout" type="zope.schema.Text"
       form:omitted="z3c.form.interfaces.IForm:true
                     z3c.form.interfaces.IAddForm:true
                     z3c.form.interfaces.IEditForm:true">
    <description i18n:translate=""
      >The layout to be used to render groups and tiles</description>
    <title i18n:translate="">Cover Layout</title>
</field>
```

as it can be seen, this field should be omitted on `z3c.form.interfaces.IAddForm` but that's not happening and I don't know why.

it's important to note that this happens only while running tests; the field is normally hidden when accessing the add form in a browser.

IMO this field must be redefined as `readonly` instead of being hidden all over the place.

**Comment by hvelarde** [comment]
@davisagli @datakurre @mauritsvanrees any hints here on why this is happening?

**Comment by datakurre** [comment]
Would you be able to check if it works with earlier plone.autoform versions?

**Comment by idgserpro** [comment]
@datakurre you can check the problem from a plone.app.testing perspective in https://github.com/plone/plone.app.testing/issues/39.

**Comment by hvelarde** [comment]
@datakurre I already did that with no luck; Plone 4.3.12 was using `plone.autoform = 1.6.2` also and we saw the error there.
