### ISSUE TITLE
Purge configuration when delete tile

### ISSUE THREAD

**Issue by rodfersou** [collective/collective.cover#765]
Steps to reproduce:

* Add new tile
* Go to compose tab
* Edit configuration opening Edit URL in new tab (and keep this URL saved)
* Delete tile
* Visit again the URL, and the data is still there

**Comment by hvelarde** [comment]
this is a critical issue we must fix ASAP; an upgrade step to clean all existing cover objects will be needed.

**Comment by rodfersou** [comment]
Well, we already [handle annotation deletion](https://github.com/collective/collective.cover/blob/master/src/collective/cover/tiles/base.py#L144-L145) in [this view](https://github.com/collective/collective.cover/blob/master/src/collective/cover/browser/compose.py#L177-L193) that is called by this [ajax request](https://github.com/collective/collective.cover/blob/445db248ac5e10cb54d3bcc70fb3a8b9381d4730/src/collective/cover/static/js/layout_edit.js#L310-L322), but it looks like we have a big mess in the javascript event registration:

![image](https://user-images.githubusercontent.com/131209/32811642-feab8e78-c987-11e7-91d9-1583414c25c7.png)

There are many events registered in the close button, and probably one of them has the instruction `e.preventDefault()` what makes the next other events don't happen.

By the way I also noticed that the Delete view should be in `layout.py`, not `compose.py` file.

**Comment by hvelarde** [comment]
I can confirm this is an issue and that the [delete()]((https://github.com/collective/collective.cover/blob/1.6b4/src/collective/cover/tiles/base.py#L138-L157)) method is never reached when clicking the delete icon on the layout screen.

this is what I did:

* create a cover with a layout of multiple rows and columns
* add some tiles to the layout
* configure the tiles pressing the Save button
* delete the tiles and repeat the operations a couple of times

for every tile with a configuration saved an annotation is created and these are never deleted; after some tests I can see the following stored in the annotations even as no tile was left in the layout:

```python
(Pdb) self.annotations
{'plone.tiles.configuration.c218d0eb-e896-4465-898a-a25cca9e1599': {'description': {'order': u'1', 'visibility': u'on'}, 'title': {'htmltag': u'h2', 'order': u'0', 'visibility': u'on'}, 'css_class': u'tile-default', 'image': {'position': u'left', 'imgsize': u'mini 200:200', 'visibility': u'on', 'order': u'2'}, 'subjects': {'order': u'4', 'visibility': u'on'}, 'date': {'order': u'3', 'visibility': u'on', 'format': u'datetime'}}, 'plone.tiles.configuration.e88dcdd1-3132-4044-9757-9079dc35ce75': {'count': {'order': u'2', 'visibility': u'on', 'offset': u''}, 'description': {'order': u'4', 'visibility': u'on'}, 'title': {'visibility': u'on', 'order': u'3', 'htmltag': u'h2'}, 'css_class': u'tile-default', 'image': {'position': u'left', 'imgsize': u'mini 200:200', 'visibility': u'on', 'order': u'5'}, 'date': {'order': u'6', 'visibility': u'on', 'format': u'datetime'}, 'autoplay': {'order': u'10', 'visibility': u'on'}}, 'plone.tiles.configuration.f416a80e-00ca-4971-8100-8f2c438ac1e4': {'css_class': u'tile-default', 'embed': {'order': u'1', 'visibility': u'on'}, 'description': {'order': u'3', 'visibility': u'on'}, 'title': {'htmltag': u'h2', 'order': u'2', 'visibility': u'on'}}, 'plone.tiles.configuration.f0d019f9-2113-4460-8d34-a4a73d5b2bee': {'css_class': u'tile-default', 'image': {'position': u'left', 'order': u'2', 'visibility': u'on', 'imgsize': u'mini 200:200'}, 'remote_url': {'visibility': u'on', 'order': u'3', 'htmltag': u'h2'}, 'title': {'visibility': u'on', 'order': u'1', 'htmltag': u'h2'}}, 'plone.tiles.configuration.d1a8beed-3d60-49ab-a121-18f3272ad5fc': {'description': {'order': u'2', 'visibility': u'on'}, 'title': {'htmltag': u'h2', 'order': u'0', 'visibility': u'on'}, 'css_class': u'tile-default', 'image': {'position': u'left', 'imgsize': u'mini 200:200', 'visibility': u'on', 'order': u'3'}, 'subjects': {'order': u'5', 'visibility': u'on'}, 'date': {'order': u'4', 'visibility': u'on', 'format': u'datetime'}}, 'plone.tiles.configuration.cdbea25a-9267-4ed1-88ac-e166521dcc74': {'css_class': u'tile-default', 'image': {'position': u'left', 'order': u'2', 'visibility': u'on', 'imgsize': u'mini 200:200'}, 'remote_url': {'htmltag': u'h2', 'order': u'3', 'visibility': u'on'}, 'title': {'htmltag': u'h2', 'order': u'1', 'visibility': u'on'}}, 'plone.tiles.configuration.a2f80390-e050-4d46-b860-5bff4b018730': {'description': {'order': u'3', 'visibility': u'on'}, 'footer': {'visibility': u'on', 'order': u'9', 'htmltag': u'h2'}, 'css_class': u'tile-default', 'image': {'position': u'left', 'imgsize': u'mini 200:200', 'visibility': u'on', 'order': u'5'}, 'title': {'htmltag': u'h2', 'order': u'2', 'visibility': u'on'}, 'header': {'htmltag': u'h2', 'order': u'1', 'visibility': u'on'}, 'offset': {'order': u'7', 'visibility': u'on', 'offset': u'0'}, 'date': {'order': u'4', 'visibility': u'on', 'format': u'datetime'}, 'number_to_show': {'order': u'6', 'visibility': u'on', 'size': u'5'}}, 'plone.locking': {u'plone.locking.stealable': {'token': '0.669065979675-0.748021800103-00105A989226:1510872362.434', 'type': <plone.locking.interfaces.LockType object at 0x7fdc988547d0>}}}
(Pdb) len(self.annotations)
8
```

this must grow exponentially with every checkout/checkin operation.

this is very serious and seems to me not  easy to fix.

**Comment by rodfersou** [comment]
IMHO the delete view should be removed, it don't make sense to do this kind of deletion while the layout is still not saved.  It brings a bad behavior.. while you don't push the save button it is not expected to delete anything (this is MY understanding of this view).

The check should be moved into SAVE button, when you save the tile, you do a check if there is any annotation that don't belongs to any active tile, and remove it.

**Comment by hvelarde** [comment]
the problem is tile configuration is saved on a tile basis; the Save button on the layout saves only changes to the layout itself.
