### ISSUE TITLE
Cant add content on tab compose 

### ISSUE THREAD

**Issue by makelli** [collective/collective.cover#772]
I cant add content on tab compose cause the content tree is empty. 

![adicionarconteudo](https://user-images.githubusercontent.com/8375257/34039325-ce361030-e16d-11e7-8d07-1682b5146aea.png)

**Comment by hvelarde** [comment]
you're not providing enough information; this has automated tests that run on every commit and is working fine in all of our deployments.

**Comment by idgserpro** [comment]
@makelli  probably a JS error is occurring. Please check the console.

**Comment by makelli** [comment]
No log about it. Its happens with some users only!. Any suggestion

**Comment by hvelarde** [comment]
@makelli you have to do your part, telling that "happens with some users only" doesn't help neither.

maybe those users don't have permission to view those files? that has nothing to do with collective.cover, it's Plone normal and expected behavior.

**Comment by makelli** [comment]
Only manager users can see the tab content tree. Member user only see tab recent itens.

**Comment by hvelarde** [comment]
IMO, that confirms my guess that you're having a permissions issue.
