### ISSUE TITLE
KeyError: 'imaging_properties' configuring carousel tile

### ISSUE THREAD

**Issue by Estevangomez** [collective/collective.cover#781]
Hi, I'm using plone 5.1 and installed collective.cover but when inserting images in the Carousel the image gets blurred 
the images loses resolution independent of size, how can I fix it ???
and also clicking on the carousel settings icon appears only one blank line nothing more like the image below:
![capturar](https://user-images.githubusercontent.com/37623432/39583355-eb8374d0-4ebd-11e8-9955-cfcdd6ded1df.PNG)

**Comment by idgserpro** [comment]
@Estevangomez we have more Plone 5 issues in https://github.com/collective/collective.cover/issues/642. Are you familiar with Plone development? We can really get a hand for fixing these issues.

**Comment by rodfersou** [comment]
IIRC there is a vocabulary to get the image sizes, what can make this template work in both versions of plone.
