### ISSUE TITLE
Plone 5  - Attribute error when check robots.txt

### ISSUE THREAD

**Issue by rodfersou** [collective/collective.cover#792]
Hey guys, sometimes I get this traceback, any glue about it?

```
2018-08-07 10:34:42 ERROR Zope.SiteErrorLog 1533648882.980.619638373703 http://localhost:8081/robots.txt
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module Products.PDBDebugMode.runcall, line 70, in pdb_runcall
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.CMFPlone.browser.robots, line 24, in __call__
  Module plone.memoize.view, line 68, in memogetter
  Module plone.app.layout.globals.portal, line 47, in portal_url
AttributeError: 'NoneType' object has no attribute 'absolute_url'
```

**Comment by idgserpro** [comment]
Aren't you having the problem described in https://github.com/plone/Products.CMFPlone/issues/1887#issuecomment-269559994?

> The problem is that that http://www.lwhsboosters.org is not a Plone Site: it is the Zope root object.

Isn't analogous to using `http://localhost:8081/robots.txt` in your example?

**Comment by rodfersou** [comment]
@idgserpro I don't think so.. this exception shows from time to time when I keep up a Plone 5 version of this builldout and play with the site..

What is more weird is that is looks like a mandelbug, I could not find a way to always reproduce the problem.

**Comment by hvelarde** [comment]
that doesn't seem related with cover; open a thread on the forum.

**Comment by rodfersou** [comment]
done https://community.plone.org/t/attribute-error-when-check-robots-txt/7007
