### ISSUE TITLE
On Plone 5, content chooser tree is always empty

### ISSUE THREAD

**Issue by rodfersou** [collective/collective.cover#797]
![image](https://user-images.githubusercontent.com/131209/43910785-215e0fe4-9bd4-11e8-83f9-50194cdac832.png)

**Comment by rodfersou** [comment]
@hvelarde rewrite this could be the first experience with Vue.js or React (since Plone community is moving to React stack)

**Comment by hvelarde** [comment]
I think Vue.js is better suited for this.

**Comment by scmos** [comment]
I just reviewed the issue and it is corrected in plone 5.1.5 and collective.cover 2.2.0

![image](https://user-images.githubusercontent.com/29259948/66428918-94cc3a80-e9dc-11e9-97a7-31db372fd5e3.png)
