### ISSUE TITLE
Mobile menu stops working when cover is installed in Plone 5

### ISSUE THREAD

**Issue by agnogueira** [collective/collective.cover#807]
1. Create a new Plone 5 site;
2. Install collective cover;
3. Go to a mobile view of the site;
4. Click on the MENU button to show navigation links;

RESULT:  the menu is not displayed as expected

collective.cover 1.7b4.dev0

Plone 5.1.2.1 (5112)
CMF 2.2.12
Zope 2.13.27
Python 2.7.12 (default, Nov 20 2017, 18:23:56) [GCC 5.4.0 20160609]
PIL 4.3.0 (Pillow)

Plone:
![menu-plone](https://user-images.githubusercontent.com/1030139/44167451-87e7db80-a0a4-11e8-9641-0b4c206c4816.png)

Plone + Cover:
![menu-cover](https://user-images.githubusercontent.com/1030139/44167470-97ffbb00-a0a4-11e8-8154-1fe43f01fe98.png)

**Comment by rodfersou** [comment]
it is working as expected in the master branch
