### ISSUE TITLE
Versioning Policy

### ISSUE THREAD

**Issue by tisto** [collective/collective.cover#843]
We took over a client that is using an old version of collective.cover (1.0a11) and I am currently looking into how to upgrade. I have to admit that I am a bit confused by the versioning policy of c.cover. I don't see a single final version even though this package is used in production since quite a while. This makes it impossible to figure out which version is safe to use and which one is not. Also, you can't tell from the versions what to expect from upgrades. 

When I upgrade from 1.6b5 to 1.7b1 what would I have to expect? Is that a feature release? A breaking change? A bugfix? Semantic versioning fixes this. You are free not to use it. Though, if you don't use it, it would be really helpful if each release would contain at least some pointers about what to expect...

**Comment by idgserpro** [comment]
For this package, I suggest reading the CHANGES.rst thoroughly. There are a bunch of warnings specially about removed dependencies between it's versions. For example:

> 1.1b1 (2016-03-31) Warning This release removes some packages from the list of dependencies. Be sure to read the whole changelog and apply the related changes to your buildout configuration while upgrading. Also, note that we have reorganized the static resources contained here; as some of them are not registered in Resource Registry tools, you could end with a broken layout if you don't clear your intermediate caches.

> Warning If you are upgrading plone.app.tiles note that latests versions of this package no longer depend on plone.app.drafts. You should explicitly add plone.app.drafts to the eggs part of your buildout configuration to avoid issues. You can safely uninstall plone.app.drafts after that, if you are not using it. Adapters used to get the items inside a folder or the results of the query in a collection were deprecated. The following classes will be removed in collective.cover v1.7: ICoverUIDsProvider, CollectionUIDsProvider, FolderUIDsProvider and GenericUIDsProvider.

**Comment by hvelarde** [comment]
@tisto we are using semantic versioning since a while; the package is in beta because there are many visual issue in the user interface that need to be fixed before a final release. going from 1.6b5 to 1.7b1 means a lot of new features and bug fixes have been added; the package is pretty stable and has been used in production in multiple government and news media sites for years.

as I mentioned in the other issue, you must upgrade Plone also, as there were some fixes in z3c.form related packages and other widgets that are needed but I don't remember, as we only test against latest Plone version.

**Comment by tisto** [comment]
@hvelarde @idgserpro I am aware that I can go through every single entry in the changelog that is distributed across two different files. My point is that with semantic versioning I don't have to because the semantic versions indicate when I have to expect a breaking change that I need to investigate. Semantic versioning says that as soon as you use a package in production it should be 1.0. When you stay in alpha/beta for ages and do not dare to use real semantic versions, you lose all the advantages of semantic versioning. Please think about how you would react, if all Plone add-on packages would use a release policy like c.cover and the individual authors would just recommend to go through all the changelogs. 

My recommendation would be to do a final release asap and then start with real semantic versioning to save yourself and everybody else lots of time. An upgrade guide like this also helps a lot: https://plonerestapi.readthedocs.io/en/latest/upgrade-guide.html

**Comment by hvelarde** [comment]
@tisto no, what [semver says](https://semver.org/#how-do-i-know-when-to-release-100) is the following:

> If your software is being used in production, it should **probably** already be 1.0.0.

anyway, I'm not against releasing a final version ASAP, if you think this could be good for others.
