### ISSUE TITLE
Limit of items in highlighted on the carousel

### ISSUE THREAD

**Issue by IolaneAndrade** [collective/collective.cover#847]
Hello,
I have a question regarding the News limit that can be highlighted on the carousel.
Currently only 5 are displayed, even if the list has more than 5 news items.
Is this a bug or a product requirement?

I found these old issues  [447](https://github.com/collective/collective.cover/issues/447) and [802](https://github.com/collective/collective.cover/pull/802)
that talked about it, but the discourses were left behind

is there an intention to change this behavior?

**[version: collective.cover = 2.1b2]**

**Comment by hvelarde** [comment]
yes, that need to be fixed but the solution proposed was not accepted.
