### ISSUE TITLE
What's the motivation of branch 1.x?

### ISSUE THREAD

**Issue by idgserpro** [collective/collective.cover#849]
Is 1.x created so it's stuck in Plone 4 and 2.x onwards is going to be for Plone 5? Or does it have something about `Versioning Policy` https://github.com/collective/collective.cover/issues/843?  Can we have this clarification added to the README somewhere?

**Comment by hvelarde** [comment]
I can't remember right now; I think it has to do with the profile versioning or keeping compatibility with some sites that use some features already removed in 2.x.

maybe @rodfersou remembers something else.

**Comment by rodfersou** [comment]
Remove deprecated adapters https://github.com/collective/collective.cover/blob/master/CHANGES.rst#20b1-2018-08-24

**Comment by idgserpro** [comment]
I think this could be a nice addition to the README, so people will know if they need to use 1.x or 2.x.

**Comment by hvelarde** [comment]
everybody needs to use 2.x, end of story ;-)
