### ISSUE TITLE
Should layoutedit tab be available to editors as well?

### ISSUE THREAD

**Issue by idgserpro** [collective/collective.cover#855]
In old collective.cover versions, default permissions were used for the layout tab, like `Modify portal content`. As defined by https://docs.plone.org/develop/plone/security/standard_permissions.html:

> cmf.ModifyPortalContent (Modify portal content)
> used to control write access to content items;

> Editor, aka Can edit,
> confers the right to edit content. As a rule of thumb, the Editor role should have the Modify portal content permission if the Owner roles does.

Since this commit https://github.com/collective/collective.cover/commit/d0d5f47733be3dbe2a0f725361600c5a50fbfba6#diff-930769023798c0b6ea6a070619d60f17 and the creation of specific permissions, the rolemap now only gives these permissions to [`Manager` and `Site Administrator`](https://github.com/collective/collective.cover/blob/060765a51d932bbd587e95ba63be9e6c3687660d/src/collective/cover/profiles/default/rolemap.xml).

Is this the intended behavior now, or this commit missed to put the `Editor` in `Can Edit Layout`?

I know this is really old @mauritsvanrees, but would you be able to answer it? We're upgrading some old installations and this would be nice to know so we can see if this needs to be a change in collective.cover and not a local policy configuration.

**Comment by mauritsvanrees** [comment]
This is intended behavior:
- Editors should only be able to add and edit tiles.
- Only Managers and Site Administrators should be able to define the layout: rows and columns.

(I am not sure from the top of my head where the exact split is between what we allow editors to do and what Managers, but the above would be the rough idea.)

**Comment by idgserpro** [comment]
I just thought that adding `Site Administrator` to just edit some specific content is too much. I know that from a logic perspective editors should only add and edit tiles, but the `edit` functionality in a cover is actually almost useless. I see no harm in letting Editors define the layout since you can have multiple covers across the whole website. Should a new rolemap be added, perhaps?

**Comment by mauritsvanrees** [comment]
This is the default. You can change it on individual sites if you want, either in a `rolemap.xml` in a site-specific package, or by clicking in the ZMI `manage_access`.

**Comment by mauritsvanrees** [comment]
For clarity: there *is* harm, potentially anyway: Editors can mess up your site design and well-thought-out corporate identity if they can change the layout. Depending on who your editors are, you could allow this.
