### ISSUE TITLE
Carousel accept all type elements

### ISSUE THREAD

**Issue by scmos** [collective/collective.cover#863]
It is allowed to drag elements that are not images. After dragging an image element the carousel fails.

![issue_862](https://user-images.githubusercontent.com/29259948/65532656-d8de1c00-dec1-11e9-9c9e-43384176b124.gif)

**Comment by hvelarde** [comment]
I don't remember why, but that's the expected behavior and not an issue:

https://github.com/collective/collective.cover/blob/master/src/collective/cover/tests/test_carousel_tile.py#L39-L40

**Comment by idgserpro** [comment]
@scmos I couldn't reproduce the problem. Can you upload the image you are trying to drag?

**Comment by scmos** [comment]
> I don't remember why, but that's the expected behavior and not an issue:
> 
> https://github.com/collective/collective.cover/blob/81ea5ba2d97f93e0023ac0cd3b3ad64e31f6ae54/src/collective/cover/tests/test_carousel_tile.py#L39-L40

I just checked the behavior and it is expected. No issue.
