### ISSUE TITLE
Plone5.2 and Python2.7 support

### ISSUE THREAD

**Issue by cleberjsantos** [collective/collective.cover#891]

**Comment by cleberjsantos** [comment]
WIP: https://github.com/collective/collective.cover/tree/plone52

**Comment by wesleybl** [comment]
@cleberjsantos thanks for your work! I am interested in getting collective.cover working on Plone 5.2 in the near future. Do you really think it's necessary to maintain Python 2 support? Can I continue your work from copy of your branch?

@hvelarde , are the changes on this branch OK for you?

**Comment by cleberjsantos** [comment]
@wesleybl I not consider it ready for use in Plone 5.2 with Python3, currently we use collective.cover with Plone5.2 and Python 2.7 (Demo. https://idgx.dev/), we chose to run it that way, because some requeriments of collective.cover that are not compatible with Python 3 ( Eg. https://github.com/collective/collective.cover/issues/747) and we lacked time to fix everything.

But my plan is to fix these issues to also migrate everything to Plone5.2 and Python3, and, yes, you can continue contribute, it will be very worthwhile for all :)

**Comment by hvelarde** [comment]
@wesleybl IIRC you have to work over 2 different issues to bring Python 3 compatibility closer; check:

https://github.com/collective/collective.cover/issues?q=is%3Aissue+is%3Aopen+label%3A%22python+3%22

the rest of the code base must already work OOTB.

**Comment by mauritsvanrees** [comment]
I checked out the `plone52` branch, but it fails to startup, complaining about a missing file `src/collective/cover/browser/static/resources.pt`. @cleberjsantos do you have an uncommitted file locally?

**Comment by mauritsvanrees** [comment]
`src/collective/cover/browser/static/` is in the `.gitignore` file, that explains why you did not see that the file needed to be committed.

**Comment by cleberjsantos** [comment]
@mauritsvanrees  This file is generated automatically by  WebPack (https://github.com/collective/collective.cover/blob/plone52/webpack/app/resources.pt).

Eg.

https://github.com/forcontent/idgx.buildout/blob/master/development.cfg#L137
https://github.com/forcontent/idgx.buildout/blob/master/development.cfg#L143

**Comment by mauritsvanrees** [comment]
Ah, right, I can't just use a checkout, I have to run webpack first. Thanks.

**Comment by mauritsvanrees** [comment]
Anyway, a few [dependencies do not work yet on Python 3](#issuecomment-916486741), which is what I want to run it on, so for the moment this is a too big hurdle.

**Comment by cleberjsantos** [comment]
My plan is to fix these issues to also migrate everything to Plone5.2 and Python3, we chose to run it that way, because some requeriments of collective.cover that are not compatible with Python 3 ( Eg. #747), but, soon :)

**Comment by wesleybl** [comment]
@cleberjsantos I rebase with the master. I think we can create a PR so that they are not more changes than they already have.

**Comment by wesleybl** [comment]
@cleberjsantos I rebase again. Please open a PR.

**Comment by wesleybl** [comment]
This was done in #900
